export function renderViewerHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>What I've Done Viewer</title>
    <link rel="stylesheet" href="/viewer.css" />
  </head>
  <body>
    <div class="app-shell">
      <header class="hero">
        <div>
          <p class="eyebrow">Local Workflow Viewer</p>
          <h1>What I've Done</h1>
          <p class="hero-copy">
            Watch the resident agent, the latest live analysis, and the stored day/week snapshots in one local view.
          </p>
        </div>
        <div class="hero-actions">
          <label class="control">
            <span>Window</span>
            <select id="window-select">
              <option value="day">Today</option>
              <option value="week">This Week</option>
              <option value="all">All Time</option>
            </select>
          </label>
          <label class="control">
            <span>Date</span>
            <input id="date-input" type="date" />
          </label>
          <button id="refresh-button" type="button">Refresh</button>
        </div>
      </header>

      <div id="error-banner" class="error-banner hidden"></div>

      <section class="panel status-panel">
        <div>
          <p class="panel-label">Agent</p>
          <p id="agent-status" class="status-pill">Loading</p>
        </div>
        <div>
          <p class="panel-label">Ingest Server</p>
          <p id="server-status" class="panel-value">-</p>
        </div>
        <div>
          <p class="panel-label">Collectors</p>
          <p id="collector-status" class="panel-value">-</p>
        </div>
        <div>
          <p class="panel-label">Last Refreshed</p>
          <p id="generated-at" class="panel-value">-</p>
        </div>
      </section>

      <section id="summary-grid" class="summary-grid"></section>

      <main class="content-grid">
        <section class="panel">
          <div class="section-header">
            <div>
              <p class="section-title">Highlights</p>
              <p class="section-subtitle">A quick pass over what stands out in the selected window.</p>
            </div>
          </div>
          <div id="highlights-grid" class="highlights-grid"></div>
        </section>

        <section class="panel">
          <div class="section-header">
            <div>
              <p class="section-title">Latest Snapshots</p>
              <p class="section-subtitle">Stored day/week summaries generated by the resident scheduler.</p>
            </div>
          </div>
          <div id="snapshot-list" class="card-list"></div>
        </section>

        <section class="panel">
          <div class="section-header">
            <div>
              <p class="section-title">Confirmed Workflows</p>
              <p class="section-subtitle">Repeated workflows that currently meet the clustering threshold.</p>
            </div>
          </div>
          <div id="workflow-list" class="table-shell"></div>
        </section>

        <section class="panel">
          <div class="section-header">
            <div>
              <p class="section-title">Emerging Workflows</p>
              <p class="section-subtitle">Early signals that still need more repeated sessions.</p>
            </div>
          </div>
          <div id="emerging-workflow-list" class="card-list"></div>
        </section>

        <section class="panel panel-span-2">
          <div class="section-header">
            <div>
              <p class="section-title">Sessions</p>
              <p class="section-subtitle">Recent live-analysis sessions for the selected window.</p>
            </div>
          </div>
          <div class="sessions-layout">
            <div id="session-list" class="session-list"></div>
            <div id="session-detail" class="session-detail empty-detail">
              Select a session to inspect the ordered steps.
            </div>
          </div>
        </section>
      </main>
    </div>

    <script type="module" src="/viewer.js"></script>
  </body>
</html>
`;
}

export function renderViewerCss(): string {
  return `
:root {
  color-scheme: light;
  --bg: #f4efe5;
  --bg-accent: #e4f0ea;
  --panel: rgba(255, 252, 247, 0.88);
  --panel-border: rgba(51, 64, 52, 0.12);
  --text: #1d241f;
  --muted: #5d685f;
  --accent: #0f766e;
  --accent-soft: rgba(15, 118, 110, 0.12);
  --warn: #b45309;
  --error: #b91c1c;
  --shadow: 0 18px 50px rgba(38, 45, 40, 0.09);
  --radius-lg: 24px;
  --radius-md: 16px;
  --radius-sm: 12px;
  --font-sans: "IBM Plex Sans", "Noto Sans KR", "Segoe UI", sans-serif;
  --font-mono: "IBM Plex Mono", "SFMono-Regular", monospace;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  font-family: var(--font-sans);
  color: var(--text);
  background:
    radial-gradient(circle at top left, rgba(255, 255, 255, 0.8), transparent 30%),
    radial-gradient(circle at top right, rgba(15, 118, 110, 0.12), transparent 24%),
    linear-gradient(180deg, var(--bg) 0%, var(--bg-accent) 100%);
}

button,
select,
input {
  font: inherit;
}

.app-shell {
  width: min(1280px, calc(100% - 32px));
  margin: 0 auto;
  padding: 28px 0 40px;
}

.hero {
  display: flex;
  justify-content: space-between;
  gap: 24px;
  padding: 28px;
  border-radius: 32px;
  background: linear-gradient(135deg, rgba(255, 252, 247, 0.96), rgba(232, 244, 239, 0.9));
  box-shadow: var(--shadow);
  border: 1px solid rgba(51, 64, 52, 0.08);
}

.eyebrow,
.panel-label,
.section-title {
  margin: 0;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  font-size: 0.74rem;
}

.eyebrow,
.panel-label {
  color: var(--muted);
}

.hero h1 {
  margin: 8px 0 10px;
  font-size: clamp(2rem, 5vw, 3.6rem);
  line-height: 0.95;
}

.hero-copy {
  margin: 0;
  max-width: 56ch;
  color: var(--muted);
  line-height: 1.6;
}

.hero-actions {
  display: flex;
  gap: 12px;
  align-items: end;
  flex-wrap: wrap;
}

.control {
  display: grid;
  gap: 6px;
  min-width: 148px;
}

.control span {
  font-size: 0.84rem;
  color: var(--muted);
}

select,
input,
button {
  min-height: 44px;
  border-radius: 14px;
  border: 1px solid rgba(29, 36, 31, 0.12);
  background: rgba(255, 255, 255, 0.9);
  color: var(--text);
  padding: 0 14px;
}

button {
  cursor: pointer;
  border: none;
  background: linear-gradient(135deg, #0f766e, #155e75);
  color: white;
  font-weight: 600;
  box-shadow: 0 10px 24px rgba(21, 94, 117, 0.24);
}

.error-banner {
  margin-top: 18px;
  padding: 14px 18px;
  border-radius: var(--radius-md);
  background: rgba(185, 28, 28, 0.1);
  border: 1px solid rgba(185, 28, 28, 0.15);
  color: var(--error);
}

.hidden {
  display: none;
}

.status-panel,
.summary-grid,
.content-grid {
  margin-top: 18px;
}

.panel,
.summary-card {
  background: var(--panel);
  border: 1px solid var(--panel-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow);
  backdrop-filter: blur(10px);
}

.status-panel {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 16px;
  padding: 22px 24px;
}

.status-pill {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin: 10px 0 0;
  padding: 8px 12px;
  border-radius: 999px;
  background: var(--accent-soft);
  color: var(--accent);
  font-weight: 700;
}

.status-pill::before {
  content: "";
  width: 10px;
  height: 10px;
  border-radius: 999px;
  background: currentColor;
}

.status-pill.degraded {
  background: rgba(180, 83, 9, 0.12);
  color: var(--warn);
}

.status-pill.stopped,
.status-pill.stale {
  background: rgba(185, 28, 28, 0.12);
  color: var(--error);
}

.panel-value {
  margin: 10px 0 0;
  font-size: 1.05rem;
  font-weight: 600;
}

.summary-grid {
  display: grid;
  grid-template-columns: repeat(5, minmax(0, 1fr));
  gap: 16px;
}

.summary-card {
  padding: 18px 20px;
}

.summary-card .value {
  margin: 10px 0 6px;
  font-size: clamp(1.3rem, 3vw, 2rem);
  font-weight: 700;
  line-height: 1;
}

.summary-card .note {
  margin: 0;
  color: var(--muted);
  font-size: 0.9rem;
  line-height: 1.5;
}

.content-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 18px;
}

.panel {
  padding: 22px;
}

.panel-span-2 {
  grid-column: 1 / -1;
}

.section-header {
  display: flex;
  align-items: end;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 16px;
}

.section-title {
  color: var(--accent);
}

.section-subtitle {
  margin: 8px 0 0;
  color: var(--muted);
  line-height: 1.5;
}

.highlights-grid,
.card-list {
  display: grid;
  gap: 12px;
}

.highlight-card,
.snapshot-card {
  padding: 16px 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.highlight-card h3,
.snapshot-card h3 {
  margin: 0 0 8px;
  font-size: 1rem;
}

.highlight-card p,
.snapshot-card p {
  margin: 0;
  color: var(--muted);
  line-height: 1.5;
}

.table-shell {
  overflow-x: auto;
}

.emerging-grid {
  display: grid;
  gap: 12px;
}

.emerging-card {
  border-radius: var(--radius-md);
  border: 1px solid rgba(29, 36, 31, 0.08);
  background: rgba(255, 255, 255, 0.78);
  overflow: hidden;
}

.emerging-card[open] {
  border-color: rgba(15, 118, 110, 0.2);
  box-shadow: inset 0 0 0 1px rgba(15, 118, 110, 0.05);
}

.emerging-summary {
  display: grid;
  gap: 12px;
  list-style: none;
  cursor: pointer;
  padding: 16px 18px;
}

.emerging-summary::-webkit-details-marker {
  display: none;
}

.emerging-summary-top {
  display: flex;
  align-items: start;
  justify-content: space-between;
  gap: 16px;
}

.emerging-summary h3 {
  margin: 0 0 6px;
  font-size: 1rem;
}

.emerging-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.emerging-stat {
  display: inline-flex;
  align-items: center;
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(244, 239, 229, 0.9);
  color: var(--muted);
  font-size: 0.84rem;
}

.emerging-toggle {
  flex-shrink: 0;
  color: var(--accent);
  font-size: 0.84rem;
  font-weight: 600;
}

.emerging-preview {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.step-preview {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 8px;
}

.step-pill {
  display: inline-flex;
  align-items: center;
  min-height: 32px;
  max-width: 100%;
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(15, 118, 110, 0.08);
  color: #155e75;
  font-size: 0.84rem;
  line-height: 1.35;
  white-space: normal;
  overflow-wrap: anywhere;
}

.step-pill.more {
  background: rgba(29, 36, 31, 0.08);
  color: var(--muted);
}

.emerging-body {
  display: grid;
  gap: 14px;
  padding: 0 18px 18px;
}

.emerging-body-copy {
  margin: 0;
  color: var(--muted);
  line-height: 1.6;
}

.emerging-step-list {
  display: grid;
  gap: 10px;
  max-height: 280px;
  overflow: auto;
  padding-right: 4px;
}

.emerging-step {
  display: grid;
  grid-template-columns: 34px 1fr;
  gap: 10px;
  align-items: start;
}

.emerging-step-index {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 34px;
  height: 34px;
  border-radius: 999px;
  background: rgba(15, 118, 110, 0.12);
  color: var(--accent);
  font-size: 0.82rem;
  font-weight: 700;
}

.emerging-step-card {
  padding: 10px 12px;
  border-radius: var(--radius-sm);
  background: rgba(244, 239, 229, 0.66);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.emerging-step-card p {
  margin: 0;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  padding: 12px 10px;
  border-bottom: 1px solid rgba(29, 36, 31, 0.08);
  text-align: left;
  vertical-align: top;
}

th {
  color: var(--muted);
  font-size: 0.82rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

td strong {
  display: block;
  margin-bottom: 4px;
}

.muted {
  color: var(--muted);
}

.mono {
  font-family: var(--font-mono);
}

.sessions-layout {
  display: grid;
  grid-template-columns: minmax(280px, 360px) 1fr;
  gap: 16px;
}

.session-list {
  display: grid;
  gap: 10px;
  max-height: 640px;
  overflow: auto;
  padding-right: 4px;
}

.session-button {
  display: grid;
  gap: 8px;
  width: 100%;
  text-align: left;
  padding: 16px;
  border-radius: var(--radius-md);
  border: 1px solid rgba(29, 36, 31, 0.08);
  background: rgba(255, 255, 255, 0.78);
  color: var(--text);
  box-shadow: none;
}

.session-button.active {
  border-color: rgba(15, 118, 110, 0.28);
  background: rgba(15, 118, 110, 0.08);
}

.session-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  color: var(--muted);
  font-size: 0.88rem;
}

.session-detail {
  min-height: 260px;
  padding: 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.empty-detail {
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--muted);
}

.step-list {
  display: grid;
  gap: 10px;
  margin-top: 18px;
}

.step-card {
  padding: 12px 14px;
  border-radius: var(--radius-sm);
  background: rgba(244, 239, 229, 0.66);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.step-card p {
  margin: 0;
}

.step-card .step-meta {
  margin-top: 6px;
  color: var(--muted);
  font-size: 0.88rem;
}

.empty-state {
  padding: 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.74);
  border: 1px dashed rgba(29, 36, 31, 0.14);
  color: var(--muted);
  line-height: 1.6;
}

@media (max-width: 980px) {
  .hero,
  .status-panel,
  .summary-grid,
  .content-grid,
  .sessions-layout {
    grid-template-columns: 1fr;
  }

  .status-panel {
    display: grid;
  }

  .summary-grid {
    display: grid;
  }

  .hero {
    padding: 24px;
  }
}
`;
}

export function renderViewerJs(): string {
  return `
const state = {
  window: "day",
  date: "",
  selectedSessionId: null,
  refreshTimer: null,
};

const elements = {
  windowSelect: document.getElementById("window-select"),
  dateInput: document.getElementById("date-input"),
  refreshButton: document.getElementById("refresh-button"),
  errorBanner: document.getElementById("error-banner"),
  agentStatus: document.getElementById("agent-status"),
  serverStatus: document.getElementById("server-status"),
  collectorStatus: document.getElementById("collector-status"),
  generatedAt: document.getElementById("generated-at"),
  summaryGrid: document.getElementById("summary-grid"),
  highlightsGrid: document.getElementById("highlights-grid"),
  snapshotList: document.getElementById("snapshot-list"),
  workflowList: document.getElementById("workflow-list"),
  emergingWorkflowList: document.getElementById("emerging-workflow-list"),
  sessionList: document.getElementById("session-list"),
  sessionDetail: document.getElementById("session-detail"),
};

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function formatDateTime(value) {
  if (!value) {
    return "-";
  }

  return new Date(value).toLocaleString();
}

function formatDuration(seconds) {
  const rounded = Math.round(Number(seconds) || 0);
  const hours = Math.floor(rounded / 3600);
  const minutes = Math.floor((rounded % 3600) / 60);
  const remainingSeconds = rounded % 60;

  if (hours > 0) {
    return \`\${hours}h \${minutes}m\`;
  }

  if (minutes > 0) {
    return \`\${minutes}m \${remainingSeconds}s\`;
  }

  return \`\${remainingSeconds}s\`;
}

function setError(message) {
  if (!message) {
    elements.errorBanner.textContent = "";
    elements.errorBanner.classList.add("hidden");
    return;
  }

  elements.errorBanner.textContent = message;
  elements.errorBanner.classList.remove("hidden");
}

function buildQueryString() {
  const params = new URLSearchParams();
  params.set("window", state.window);

  if (state.date) {
    params.set("date", state.date);
  }

  return params.toString();
}

function syncUrl() {
  const url = new URL(window.location.href);
  url.search = buildQueryString();
  window.history.replaceState({}, "", url);
}

function initializeStateFromUrl() {
  const url = new URL(window.location.href);
  const selectedWindow = url.searchParams.get("window");
  const selectedDate = url.searchParams.get("date");

  if (selectedWindow === "day" || selectedWindow === "week" || selectedWindow === "all") {
    state.window = selectedWindow;
  }

  if (selectedDate) {
    state.date = selectedDate;
  }

  elements.windowSelect.value = state.window;
  elements.dateInput.value = state.date;
}

function renderStatus(agentHealth, generatedAt) {
  elements.agentStatus.textContent = agentHealth.status;
  elements.agentStatus.className = "status-pill " + agentHealth.status;

  const ingestServer = agentHealth.runtime.state && agentHealth.runtime.state.ingestServer;
  elements.serverStatus.textContent =
    ingestServer && ingestServer.status === "running"
      ? \`\${ingestServer.host}:\${ingestServer.port}\`
      : ingestServer && ingestServer.status
        ? ingestServer.status
        : "stopped";

  const collectors = agentHealth.collectors || [];

  if (collectors.length === 0) {
    elements.collectorStatus.textContent = "No collectors";
  } else {
    elements.collectorStatus.textContent = collectors.map((collector) => {
      return \`\${collector.id} (\${collector.status})\`;
    }).join(", ");
  }

  elements.generatedAt.textContent = formatDateTime(generatedAt);
}

function renderSummaryCards(data) {
  const cards = [
    {
      label: "Tracked Sessions",
      value: data.report.totalSessions,
      note: \`\${data.sessionSummaries.length} sessions listed in this live view\`,
    },
    {
      label: "Tracked Time",
      value: formatDuration(data.report.totalTrackedDurationSeconds),
      note: \`Window: \${data.timeWindow.window} on \${data.timeWindow.reportDate}\`,
    },
    {
      label: "Confirmed Workflows",
      value: data.report.workflows.length,
      note: "Repeated workflows above the current threshold",
    },
    {
      label: "Emerging Workflows",
      value: data.report.emergingWorkflows.length,
      note: "Early patterns that still need more repetition",
    },
    {
      label: "Raw Events",
      value: data.rawEventCount,
      note: data.latestEventAt ? \`Latest event at \${formatDateTime(data.latestEventAt)}\` : "No raw events yet",
    },
  ];

  elements.summaryGrid.innerHTML = cards.map((card) => {
    return \`
      <article class="summary-card">
        <p class="panel-label">\${escapeHtml(card.label)}</p>
        <p class="value">\${escapeHtml(card.value)}</p>
        <p class="note">\${escapeHtml(card.note)}</p>
      </article>
    \`;
  }).join("");
}

function highlightMarkup(title, entries, formatter) {
  if (!entries || entries.length === 0) {
    return \`
      <article class="highlight-card">
        <h3>\${escapeHtml(title)}</h3>
        <p>No items yet in this window.</p>
      </article>
    \`;
  }

  return \`
    <article class="highlight-card">
      <h3>\${escapeHtml(title)}</h3>
      \${entries.map((entry) => {
        return \`<p><strong>\${escapeHtml(entry.workflowName)}</strong> \${escapeHtml(formatter(entry))}</p>\`;
      }).join("")}
    </article>
  \`;
}

function renderHighlights(summary) {
  elements.highlightsGrid.innerHTML = [
    highlightMarkup("Top Repetitive", summary.topRepetitiveWorkflows, (entry) => {
      return \`\${entry.frequency} repeats, \${formatDuration(entry.totalDurationSeconds)} total\`;
    }),
    highlightMarkup("Time-Heavy", summary.highestTimeConsumingRepetitiveWorkflows, (entry) => {
      return \`\${formatDuration(entry.totalDurationSeconds)} total, \${entry.frequency} repeats\`;
    }),
    highlightMarkup("Quick Wins", summary.quickWinAutomationCandidates, (entry) => {
      return \`\${entry.automationSuitability} automation fit, confidence \${entry.confidenceScore}\`;
    }),
    highlightMarkup("Needs Review", summary.workflowsNeedingHumanJudgment, (entry) => {
      return \`confidence \${entry.confidenceScore}, labeled: \${entry.userLabeled ? "yes" : "no"}\`;
    }),
  ].join("");
}

function renderSnapshotList(snapshots) {
  if (!snapshots || snapshots.length === 0) {
    elements.snapshotList.innerHTML = '<div class="empty-state">No stored snapshots yet.</div>';
    return;
  }

  elements.snapshotList.innerHTML = snapshots.map((snapshot) => {
    return \`
      <article class="snapshot-card">
        <h3>\${escapeHtml(snapshot.window.toUpperCase())} snapshot</h3>
        <p>\${escapeHtml(snapshot.reportDate)} in \${escapeHtml(snapshot.timezone)}</p>
        <p>\${escapeHtml(String(snapshot.totalSessions))} sessions, \${escapeHtml(String(snapshot.workflowCount))} confirmed workflows, \${escapeHtml(String(snapshot.emergingWorkflowCount))} emerging</p>
        <p class="muted">Generated \${escapeHtml(formatDateTime(snapshot.generatedAt))}</p>
      </article>
    \`;
  }).join("");
}

function renderWorkflowTable(container, workflows, emptyMessage, isEmerging = false) {
  if (!workflows || workflows.length === 0) {
    container.innerHTML = \`<div class="empty-state">\${escapeHtml(emptyMessage)}</div>\`;
    return;
  }

  const rows = workflows.map((workflow) => {
    const previewSteps = workflow.representativeSteps.slice(0, isEmerging ? 4 : 5);
    const remainingStepCount = Math.max(0, workflow.representativeSteps.length - previewSteps.length);
    const recommendation = isEmerging ? "Needs more repeated sessions" : workflow.recommendedApproach;
    const score = isEmerging ? workflow.confidence : workflow.confidenceScore;
    const timeSpent = isEmerging ? workflow.totalDurationSeconds : workflow.totalDurationSeconds;

    return \`
      <tr>
        <td>
          <strong>\${escapeHtml(workflow.workflowName)}</strong>
          <div class="step-preview">
            \${previewSteps.map((step) => \`<span class="step-pill">\${escapeHtml(step)}</span>\`).join("")}
            \${remainingStepCount > 0 ? \`<span class="step-pill more">+\${escapeHtml(String(remainingStepCount))} more</span>\` : ""}
          </div>
        </td>
        <td>\${escapeHtml(String(workflow.frequency))}</td>
        <td>\${escapeHtml(formatDuration(workflow.averageDurationSeconds))}</td>
        <td>\${escapeHtml(formatDuration(timeSpent))}</td>
        <td>\${escapeHtml(String(score))}</td>
        <td>\${escapeHtml(recommendation)}</td>
      </tr>
    \`;
  }).join("");

  container.innerHTML = \`
    <table>
      <thead>
        <tr>
          <th>Workflow</th>
          <th>Frequency</th>
          <th>Avg Duration</th>
          <th>Total Time</th>
          <th>\${isEmerging ? "State" : "Confidence"}</th>
          <th>\${isEmerging ? "Why" : "Recommendation"}</th>
        </tr>
      </thead>
      <tbody>\${rows}</tbody>
    </table>
  \`;
}

function renderEmergingWorkflowList(container, workflows, emptyMessage) {
  if (!workflows || workflows.length === 0) {
    container.innerHTML = \`<div class="empty-state">\${escapeHtml(emptyMessage)}</div>\`;
    return;
  }

  container.innerHTML = \`
    <div class="emerging-grid">
      \${workflows.map((workflow) => {
        const previewSteps = workflow.representativeSteps.slice(0, 4);
        const remainingCount = Math.max(0, workflow.representativeSteps.length - previewSteps.length);

        return \`
          <details class="emerging-card">
            <summary class="emerging-summary">
              <div class="emerging-summary-top">
                <div>
                  <h3>\${escapeHtml(workflow.workflowName)}</h3>
                  <div class="emerging-meta">
                    <span class="emerging-stat">\${escapeHtml(String(workflow.frequency))} repeat</span>
                    <span class="emerging-stat">avg \${escapeHtml(formatDuration(workflow.averageDurationSeconds))}</span>
                    <span class="emerging-stat">total \${escapeHtml(formatDuration(workflow.totalDurationSeconds))}</span>
                    <span class="emerging-stat">\${escapeHtml(workflow.confidence)}</span>
                  </div>
                </div>
                <span class="emerging-toggle">Show steps</span>
              </div>
              <div class="emerging-preview">
                \${previewSteps.map((step) => \`<span class="step-pill">\${escapeHtml(step)}</span>\`).join("")}
                \${remainingCount > 0 ? \`<span class="step-pill more">+\${escapeHtml(String(remainingCount))} more</span>\` : ""}
              </div>
            </summary>
            <div class="emerging-body">
              <p class="emerging-body-copy">
                This pattern is still provisional. It becomes a confirmed workflow after more repeated sessions.
              </p>
              <div class="emerging-step-list">
                \${workflow.representativeSteps.map((step, index) => {
                  return \`
                    <div class="emerging-step">
                      <span class="emerging-step-index">\${escapeHtml(String(index + 1))}</span>
                      <div class="emerging-step-card">
                        <p>\${escapeHtml(step)}</p>
                      </div>
                    </div>
                  \`;
                }).join("")}
              </div>
            </div>
          </details>
        \`;
      }).join("")}
    </div>
  \`;
}

function renderSessionList(sessions) {
  if (!sessions || sessions.length === 0) {
    state.selectedSessionId = null;
    elements.sessionList.innerHTML = '<div class="empty-state">No sessions detected for this window yet.</div>';
    elements.sessionDetail.textContent = 'Select a session to inspect the ordered steps.';
    elements.sessionDetail.className = 'session-detail empty-detail';
    return;
  }

  if (!state.selectedSessionId || !sessions.some((session) => session.id === state.selectedSessionId)) {
    state.selectedSessionId = sessions[0].id;
  }

  elements.sessionList.innerHTML = sessions.map((session) => {
    const isActive = session.id === state.selectedSessionId;

    return \`
      <button class="session-button \${isActive ? "active" : ""}" type="button" data-session-id="\${escapeHtml(session.id)}">
        <strong>\${escapeHtml(session.primaryApplication)}</strong>
        <span class="session-meta">
          <span>\${escapeHtml(session.primaryDomain || "No domain")}</span>
          <span>\${escapeHtml(formatDuration(session.durationSeconds))}</span>
          <span>\${escapeHtml(String(session.stepCount))} steps</span>
        </span>
        <span class="muted">\${escapeHtml(formatDateTime(session.startTime))}</span>
      </button>
    \`;
  }).join("");

  for (const button of elements.sessionList.querySelectorAll("[data-session-id]")) {
    button.addEventListener("click", () => {
      state.selectedSessionId = button.getAttribute("data-session-id");
      renderSessionList(sessions);
      void refreshSessionDetail();
    });
  }
}

async function refreshSessionDetail() {
  if (!state.selectedSessionId) {
    elements.sessionDetail.textContent = 'Select a session to inspect the ordered steps.';
    elements.sessionDetail.className = 'session-detail empty-detail';
    return;
  }

  const response = await fetch(\`/api/viewer/sessions/\${encodeURIComponent(state.selectedSessionId)}?\${buildQueryString()}\`);

  if (!response.ok) {
    throw new Error('Failed to load session detail.');
  }

  const session = await response.json();
  const steps = (session.steps || []).map((step) => {
    const target = step.target ? \` -> \${step.target}\` : "";
    const context = [step.domain, step.titlePattern].filter(Boolean).join(" | ");

    return \`
      <article class="step-card">
        <p><strong>\${escapeHtml(String(step.order))}. \${escapeHtml(step.actionName || step.action)}</strong></p>
        <p class="step-meta">\${escapeHtml(formatDateTime(step.timestamp))} | \${escapeHtml(step.application)}\${target ? " | " + escapeHtml(target) : ""}</p>
        \${context ? \`<p class="step-meta">\${escapeHtml(context)}</p>\` : ""}
      </article>
    \`;
  }).join("");

  elements.sessionDetail.className = "session-detail";
  elements.sessionDetail.innerHTML = \`
    <div>
      <p class="panel-label">Session</p>
      <h3>\${escapeHtml(session.primaryApplication)}</h3>
      <p class="muted">\${escapeHtml(formatDateTime(session.startTime))} to \${escapeHtml(formatDateTime(session.endTime))}</p>
      <p class="muted">Boundary: \${escapeHtml(session.sessionBoundaryReason)} | \${escapeHtml(String((session.steps || []).length))} steps</p>
      <div class="step-list">\${steps || '<div class="empty-state">No steps in this session.</div>'}</div>
    </div>
  \`;
}

async function refreshDashboard() {
  setError("");
  elements.refreshButton.disabled = true;

  try {
    syncUrl();
    const response = await fetch(\`/api/viewer/dashboard?\${buildQueryString()}\`);

    if (!response.ok) {
      throw new Error("Failed to load local viewer data.");
    }

    const data = await response.json();

    if (!state.date) {
      state.date = data.timeWindow.reportDate;
      elements.dateInput.value = state.date;
      syncUrl();
    }

    renderStatus(data.agentHealth, data.generatedAt);
    renderSummaryCards(data);
    renderHighlights(data.report.summary);
    renderSnapshotList(data.latestSnapshots);
    renderWorkflowTable(
      elements.workflowList,
      data.report.workflows,
      "No confirmed workflows yet. Keep collecting data or switch to the week window.",
      false,
    );
    renderEmergingWorkflowList(
      elements.emergingWorkflowList,
      data.report.emergingWorkflows,
      "No emerging workflows yet for this window.",
    );
    renderSessionList(data.sessionSummaries);
    await refreshSessionDetail();
  } catch (error) {
    setError(error instanceof Error ? error.message : "Unknown viewer error");
  } finally {
    elements.refreshButton.disabled = false;
  }
}

function scheduleRefresh() {
  if (state.refreshTimer) {
    window.clearInterval(state.refreshTimer);
  }

  state.refreshTimer = window.setInterval(() => {
    void refreshDashboard();
  }, 30000);
}

function bindEvents() {
  elements.windowSelect.addEventListener("change", () => {
    state.window = elements.windowSelect.value;
    void refreshDashboard();
  });

  elements.dateInput.addEventListener("change", () => {
    state.date = elements.dateInput.value;
    void refreshDashboard();
  });

  elements.refreshButton.addEventListener("click", () => {
    void refreshDashboard();
  });
}

initializeStateFromUrl();
bindEvents();
scheduleRefresh();
void refreshDashboard();
`;
}
