export function renderViewerHtml(options: { viewerActionToken?: string | undefined } = {}): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="wid-viewer-action-token" content="${options.viewerActionToken ?? ""}" />
    <title>What I've Done Viewer</title>
    <link rel="stylesheet" href="/viewer.css" />
  </head>
  <body>
    <div class="app-shell">
      <header class="hero">
        <div>
          <p class="eyebrow">Local Workflow Console</p>
          <h1>What I've Done</h1>
          <p class="hero-copy">
            Move through overview, review, and analysis-ready workflow context without leaving the local viewer.
          </p>
        </div>
        <div class="hero-actions">
          <label class="control">
            <span>Window</span>
            <select id="window-select">
              <option value="day">Today</option>
              <option value="week">This Week</option>
              <option value="all">All Time</option>
            </select>
          </label>
          <label class="control">
            <span>Date</span>
            <input id="date-input" type="date" />
          </label>
          <button id="refresh-button" type="button">Refresh</button>
        </div>
      </header>

      <section class="command-bar">
        <div class="command-bar-copy">
          <p class="panel-label">Console Views</p>
          <p class="command-bar-text">
            Use the local console as a control surface: scan the live summary, review workflows, then send analysis requests in the next milestone.
          </p>
        </div>
        <nav class="viewer-nav" aria-label="Viewer sections">
          <button class="view-toggle active" data-view-target="overview" type="button">Overview</button>
          <button class="view-toggle" data-view-target="review" type="button">Review</button>
          <button class="view-toggle" data-view-target="analysis" type="button">Analysis</button>
        </nav>
      </section>

      <div id="error-banner" class="error-banner hidden"></div>

      <section class="panel status-panel">
        <div>
          <p class="panel-label">Agent</p>
          <p id="agent-status" class="status-pill">Loading</p>
        </div>
        <div>
          <p class="panel-label">Ingest Server</p>
          <p id="server-status" class="panel-value">-</p>
        </div>
        <div>
          <p class="panel-label">Collectors</p>
          <p id="collector-status" class="panel-value">-</p>
        </div>
        <div>
          <p class="panel-label">Last Refreshed</p>
          <p id="generated-at" class="panel-value">-</p>
        </div>
      </section>

      <section id="summary-grid" class="summary-grid"></section>

      <main class="view-stack">
        <section class="view-panel" data-view-panel="overview">
          <div class="content-grid">
            <section class="panel">
              <div class="section-header">
                <div>
                  <p class="section-title">Highlights</p>
                  <p class="section-subtitle">A quick pass over what stands out in the selected window.</p>
                </div>
              </div>
              <div id="highlights-grid" class="highlights-grid"></div>
            </section>

            <section class="panel">
              <div class="section-header">
                <div>
                  <p class="section-title">Latest Snapshots</p>
                  <p class="section-subtitle">Stored day/week summaries generated by the resident scheduler.</p>
                </div>
              </div>
              <div id="snapshot-list" class="card-list"></div>
            </section>

            <section class="panel panel-span-2">
              <div class="section-header">
                <div>
                  <p class="section-title">Comparison View</p>
                  <p class="section-subtitle">Compare the selected day or week against the previous matching window.</p>
                </div>
              </div>
              <div id="comparison-view" class="comparison-shell"></div>
            </section>
          </div>
        </section>

        <section class="view-panel hidden" data-view-panel="review">
          <div class="content-grid">
            <section class="panel panel-span-2">
              <div class="section-header">
                <div>
                  <p class="section-title">Feedback Queue</p>
                  <p class="section-subtitle">Review one workflow at a time without touching the CLI.</p>
                </div>
              </div>
              <div class="feedback-layout">
                <div id="feedback-workflow-list" class="feedback-workflow-list"></div>
                <div id="workflow-detail" class="workflow-detail empty-detail">
                  Select a workflow to review its current label, visibility state, and automation hints.
                </div>
              </div>
            </section>

            <section class="panel">
              <div class="section-header">
                <div>
                  <p class="section-title">Confirmed Workflows</p>
                  <p class="section-subtitle">Repeated workflows that currently meet the clustering threshold.</p>
                </div>
              </div>
              <div id="workflow-list" class="table-shell"></div>
            </section>

            <section class="panel">
              <div class="section-header">
                <div>
                  <p class="section-title">Emerging Workflows</p>
                  <p class="section-subtitle">Early signals that still need more repeated sessions.</p>
                </div>
              </div>
              <div id="emerging-workflow-list" class="card-list"></div>
            </section>

            <section class="panel panel-span-2">
              <div class="section-header">
                <div>
                  <p class="section-title">Sessions</p>
                  <p class="section-subtitle">Recent live-analysis sessions for the selected window.</p>
                </div>
              </div>
              <div class="sessions-layout">
                <div id="session-list" class="session-list"></div>
                <div id="session-detail" class="session-detail empty-detail">
                  Select a session to inspect the ordered steps.
                </div>
              </div>
            </section>
          </div>
        </section>

        <section class="view-panel hidden" data-view-panel="analysis">
          <div class="content-grid">
            <section class="panel panel-span-2">
              <div class="section-header">
                <div>
                  <p class="section-title">Analysis Surface</p>
                  <p class="section-subtitle">Run a summarized analysis request from the local console and review the latest interpretation without leaving the browser.</p>
                </div>
              </div>
              <div id="analysis-surface" class="analysis-layout">
                <div class="empty-state">Analysis readiness will appear here after the local dashboard loads.</div>
              </div>
            </section>

            <section class="panel">
              <div class="section-header">
                <div>
                  <p class="section-title">Ready Workflows</p>
                  <p class="section-subtitle">Top candidates that will be easiest to review or send for interpretation.</p>
                </div>
              </div>
              <div id="analysis-ready-list" class="card-list"></div>
            </section>

            <section class="panel panel-span-3">
              <div class="section-header">
                <div>
                  <p class="section-title">Latest Results</p>
                  <p class="section-subtitle">Stored workflow interpretations from the most recent completed manual analysis run.</p>
                </div>
              </div>
              <div id="analysis-results-list" class="card-list"></div>
            </section>
          </div>
        </section>
      </main>
    </div>

    <script type="module" src="/viewer.js"></script>
  </body>
</html>
`;
}

export function renderViewerCss(): string {
  return `
:root {
  color-scheme: light;
  --bg: #f4efe5;
  --bg-accent: #e4f0ea;
  --panel: rgba(255, 252, 247, 0.88);
  --panel-border: rgba(51, 64, 52, 0.12);
  --text: #1d241f;
  --muted: #5d685f;
  --accent: #0f766e;
  --accent-soft: rgba(15, 118, 110, 0.12);
  --warn: #b45309;
  --error: #b91c1c;
  --shadow: 0 18px 50px rgba(38, 45, 40, 0.09);
  --radius-lg: 24px;
  --radius-md: 16px;
  --radius-sm: 12px;
  --font-sans: "IBM Plex Sans", "Noto Sans KR", "Segoe UI", sans-serif;
  --font-mono: "IBM Plex Mono", "SFMono-Regular", monospace;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  font-family: var(--font-sans);
  color: var(--text);
  background:
    radial-gradient(circle at top left, rgba(255, 255, 255, 0.8), transparent 30%),
    radial-gradient(circle at top right, rgba(15, 118, 110, 0.12), transparent 24%),
    linear-gradient(180deg, var(--bg) 0%, var(--bg-accent) 100%);
}

button,
select,
input,
textarea {
  font: inherit;
}

.app-shell {
  width: min(1280px, calc(100% - 32px));
  margin: 0 auto;
  padding: 28px 0 40px;
}

.hero {
  display: flex;
  justify-content: space-between;
  gap: 24px;
  padding: 28px;
  border-radius: 32px;
  background: linear-gradient(135deg, rgba(255, 252, 247, 0.96), rgba(232, 244, 239, 0.9));
  box-shadow: var(--shadow);
  border: 1px solid rgba(51, 64, 52, 0.08);
}

.eyebrow,
.panel-label,
.section-title {
  margin: 0;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  font-size: 0.74rem;
}

.eyebrow,
.panel-label {
  color: var(--muted);
}

.hero h1 {
  margin: 8px 0 10px;
  font-size: clamp(2rem, 5vw, 3.6rem);
  line-height: 0.95;
}

.hero-copy {
  margin: 0;
  max-width: 56ch;
  color: var(--muted);
  line-height: 1.6;
}

.hero-actions {
  display: flex;
  gap: 12px;
  align-items: end;
  flex-wrap: wrap;
}

.command-bar {
  position: sticky;
  top: 16px;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-top: 18px;
  padding: 16px 20px;
  border-radius: 20px;
  background: rgba(255, 252, 247, 0.94);
  border: 1px solid rgba(51, 64, 52, 0.08);
  box-shadow: 0 12px 30px rgba(38, 45, 40, 0.08);
  backdrop-filter: blur(12px);
}

.command-bar-copy {
  display: grid;
  gap: 6px;
}

.command-bar-text {
  margin: 0;
  max-width: 64ch;
  color: var(--muted);
  line-height: 1.55;
}

.viewer-nav {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.view-toggle {
  min-height: 40px;
  padding: 0 16px;
  border: 1px solid rgba(29, 36, 31, 0.1);
  background: rgba(244, 239, 229, 0.8);
  color: var(--muted);
  box-shadow: none;
}

.view-toggle.active {
  background: linear-gradient(135deg, #0f766e, #155e75);
  color: white;
  box-shadow: 0 10px 24px rgba(21, 94, 117, 0.24);
}

.control {
  display: grid;
  gap: 6px;
  min-width: 148px;
}

.control span {
  font-size: 0.84rem;
  color: var(--muted);
}

select,
input,
textarea,
button {
  min-height: 44px;
  border-radius: 14px;
  border: 1px solid rgba(29, 36, 31, 0.12);
  background: rgba(255, 255, 255, 0.9);
  color: var(--text);
  padding: 0 14px;
}

button {
  cursor: pointer;
  border: none;
  background: linear-gradient(135deg, #0f766e, #155e75);
  color: white;
  font-weight: 600;
  box-shadow: 0 10px 24px rgba(21, 94, 117, 0.24);
}

textarea {
  min-height: 112px;
  padding: 12px 14px;
  resize: vertical;
}

.error-banner {
  margin-top: 18px;
  padding: 14px 18px;
  border-radius: var(--radius-md);
  background: rgba(185, 28, 28, 0.1);
  border: 1px solid rgba(185, 28, 28, 0.15);
  color: var(--error);
}

.hidden {
  display: none;
}

.status-panel,
.summary-grid,
.view-stack {
  margin-top: 18px;
}

.panel,
.summary-card {
  background: var(--panel);
  border: 1px solid var(--panel-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow);
  backdrop-filter: blur(10px);
}

.status-panel {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 16px;
  padding: 22px 24px;
}

.status-pill {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin: 10px 0 0;
  padding: 8px 12px;
  border-radius: 999px;
  background: var(--accent-soft);
  color: var(--accent);
  font-weight: 700;
}

.status-pill::before {
  content: "";
  width: 10px;
  height: 10px;
  border-radius: 999px;
  background: currentColor;
}

.status-pill.degraded {
  background: rgba(180, 83, 9, 0.12);
  color: var(--warn);
}

.status-pill.stopped,
.status-pill.stale {
  background: rgba(185, 28, 28, 0.12);
  color: var(--error);
}

.panel-value {
  margin: 10px 0 0;
  font-size: 1.05rem;
  font-weight: 600;
}

.summary-grid {
  display: grid;
  grid-template-columns: repeat(5, minmax(0, 1fr));
  gap: 16px;
}

.summary-card {
  padding: 18px 20px;
}

.summary-card .value {
  margin: 10px 0 6px;
  font-size: clamp(1.3rem, 3vw, 2rem);
  font-weight: 700;
  line-height: 1;
}

.summary-card .note {
  margin: 0;
  color: var(--muted);
  font-size: 0.9rem;
  line-height: 1.5;
}

.content-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 18px;
}

.view-stack {
  display: grid;
  gap: 18px;
}

.view-panel {
  display: block;
}

.view-panel.hidden {
  display: none;
}

.panel {
  padding: 22px;
}

.panel-span-2 {
  grid-column: 1 / -1;
}

.section-header {
  display: flex;
  align-items: end;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 16px;
}

.section-title {
  color: var(--accent);
}

.section-subtitle {
  margin: 8px 0 0;
  color: var(--muted);
  line-height: 1.5;
}

.highlights-grid,
.card-list {
  display: grid;
  gap: 12px;
}

.analysis-layout {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

.analysis-card {
  display: grid;
  gap: 10px;
  padding: 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.8);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.analysis-card.accent {
  background: linear-gradient(135deg, rgba(15, 118, 110, 0.12), rgba(255, 255, 255, 0.92));
  border-color: rgba(15, 118, 110, 0.18);
}

.analysis-card h3,
.analysis-ready-card h3 {
  margin: 0;
  font-size: 1.04rem;
}

.analysis-copy {
  margin: 0;
  color: var(--muted);
  line-height: 1.6;
}

.analysis-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.analysis-ready-card {
  display: grid;
  gap: 10px;
  padding: 16px 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.analysis-result-card {
  display: grid;
  gap: 10px;
  padding: 16px 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.82);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.analysis-result-card p,
.analysis-result-card h3 {
  margin: 0;
}

.analysis-result-summary {
  color: var(--muted);
  line-height: 1.6;
}

.analysis-note {
  display: grid;
  gap: 14px;
  padding: 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.analysis-note p {
  margin: 0;
  color: var(--muted);
  line-height: 1.6;
}

.analysis-action-row {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  align-items: center;
}

.analysis-toggle {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  padding: 10px 14px;
  border-radius: 999px;
  background: rgba(244, 239, 229, 0.82);
  border: 1px solid rgba(29, 36, 31, 0.08);
  color: var(--text);
  font-size: 0.92rem;
}

.analysis-toggle input {
  width: 16px;
  height: 16px;
  accent-color: var(--accent);
}

.analysis-status-copy {
  margin: 0;
  color: var(--muted);
  line-height: 1.6;
}

.highlight-card,
.snapshot-card {
  padding: 16px 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.highlight-card h3,
.snapshot-card h3 {
  margin: 0 0 8px;
  font-size: 1rem;
}

.highlight-card p,
.snapshot-card p {
  margin: 0;
  color: var(--muted);
  line-height: 1.5;
}

.table-shell {
  overflow-x: auto;
}

.emerging-grid {
  display: grid;
  gap: 12px;
}

.emerging-card {
  border-radius: var(--radius-md);
  border: 1px solid rgba(29, 36, 31, 0.08);
  background: rgba(255, 255, 255, 0.78);
  overflow: hidden;
}

.emerging-card[open] {
  border-color: rgba(15, 118, 110, 0.2);
  box-shadow: inset 0 0 0 1px rgba(15, 118, 110, 0.05);
}

.emerging-summary {
  display: grid;
  gap: 12px;
  list-style: none;
  cursor: pointer;
  padding: 16px 18px;
}

.emerging-summary::-webkit-details-marker {
  display: none;
}

.emerging-summary-top {
  display: flex;
  align-items: start;
  justify-content: space-between;
  gap: 16px;
}

.emerging-summary h3 {
  margin: 0 0 6px;
  font-size: 1rem;
}

.emerging-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.emerging-stat {
  display: inline-flex;
  align-items: center;
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(244, 239, 229, 0.9);
  color: var(--muted);
  font-size: 0.84rem;
}

.emerging-toggle {
  flex-shrink: 0;
  color: var(--accent);
  font-size: 0.84rem;
  font-weight: 600;
}

.emerging-preview {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.step-preview {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 8px;
}

.step-pill {
  display: inline-flex;
  align-items: center;
  min-height: 32px;
  max-width: 100%;
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(15, 118, 110, 0.08);
  color: #155e75;
  font-size: 0.84rem;
  line-height: 1.35;
  white-space: normal;
  overflow-wrap: anywhere;
}

.step-pill.more {
  background: rgba(29, 36, 31, 0.08);
  color: var(--muted);
}

.emerging-body {
  display: grid;
  gap: 14px;
  padding: 0 18px 18px;
}

.emerging-body-copy {
  margin: 0;
  color: var(--muted);
  line-height: 1.6;
}

.emerging-step-list {
  display: grid;
  gap: 10px;
  max-height: 280px;
  overflow: auto;
  padding-right: 4px;
}

.emerging-step {
  display: grid;
  grid-template-columns: 34px 1fr;
  gap: 10px;
  align-items: start;
}

.emerging-step-index {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 34px;
  height: 34px;
  border-radius: 999px;
  background: rgba(15, 118, 110, 0.12);
  color: var(--accent);
  font-size: 0.82rem;
  font-weight: 700;
}

.emerging-step-card {
  padding: 10px 12px;
  border-radius: var(--radius-sm);
  background: rgba(244, 239, 229, 0.66);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.emerging-step-card p {
  margin: 0;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  padding: 12px 10px;
  border-bottom: 1px solid rgba(29, 36, 31, 0.08);
  text-align: left;
  vertical-align: top;
}

th {
  color: var(--muted);
  font-size: 0.82rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

td strong {
  display: block;
  margin-bottom: 4px;
}

.muted {
  color: var(--muted);
}

.mono {
  font-family: var(--font-mono);
}

.sessions-layout {
  display: grid;
  grid-template-columns: minmax(280px, 360px) 1fr;
  gap: 16px;
}

.feedback-layout {
  display: grid;
  grid-template-columns: minmax(300px, 360px) 1fr;
  gap: 16px;
}

.comparison-shell,
.comparison-summary-grid,
.comparison-columns {
  display: grid;
  gap: 16px;
}

.comparison-summary-grid {
  grid-template-columns: repeat(4, minmax(0, 1fr));
}

.comparison-summary-card,
.comparison-column {
  padding: 16px 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.comparison-summary-card .value {
  margin: 8px 0 6px;
  font-size: 1.5rem;
  font-weight: 700;
}

.comparison-columns {
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

.comparison-column h3 {
  margin: 0 0 8px;
  font-size: 1rem;
}

.comparison-entry-list {
  display: grid;
  gap: 10px;
  margin-top: 14px;
}

.comparison-entry {
  padding: 12px 14px;
  border-radius: var(--radius-sm);
  background: rgba(244, 239, 229, 0.66);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.comparison-entry p {
  margin: 4px 0 0;
}

.feedback-workflow-list {
  display: grid;
  gap: 10px;
  max-height: 680px;
  overflow: auto;
  padding-right: 4px;
}

.workflow-review-button {
  display: grid;
  gap: 10px;
  width: 100%;
  text-align: left;
  padding: 16px;
  border-radius: var(--radius-md);
  border: 1px solid rgba(29, 36, 31, 0.08);
  background: rgba(255, 255, 255, 0.78);
  color: var(--text);
  box-shadow: none;
}

.workflow-review-button.active {
  border-color: rgba(15, 118, 110, 0.28);
  background: rgba(15, 118, 110, 0.08);
}

.workflow-review-header {
  display: flex;
  align-items: start;
  justify-content: space-between;
  gap: 12px;
}

.workflow-review-button strong,
.workflow-detail h3 {
  margin: 0;
  font-size: 1.05rem;
}

.workflow-chip-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.workflow-chip {
  display: inline-flex;
  align-items: center;
  min-height: 30px;
  padding: 6px 10px;
  border-radius: 999px;
  background: rgba(15, 118, 110, 0.08);
  color: var(--accent);
  font-size: 0.82rem;
  font-weight: 600;
}

.workflow-chip.subtle {
  background: rgba(29, 36, 31, 0.08);
  color: var(--muted);
}

.workflow-chip.warn {
  background: rgba(180, 83, 9, 0.12);
  color: var(--warn);
}

.workflow-chip.hidden-state {
  background: rgba(185, 28, 28, 0.12);
  color: var(--error);
}

.workflow-review-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  color: var(--muted);
  font-size: 0.88rem;
}

.session-list {
  display: grid;
  gap: 10px;
  max-height: 640px;
  overflow: auto;
  padding-right: 4px;
}

.session-button {
  display: grid;
  gap: 8px;
  width: 100%;
  text-align: left;
  padding: 16px;
  border-radius: var(--radius-md);
  border: 1px solid rgba(29, 36, 31, 0.08);
  background: rgba(255, 255, 255, 0.78);
  color: var(--text);
  box-shadow: none;
}

.session-button.active {
  border-color: rgba(15, 118, 110, 0.28);
  background: rgba(15, 118, 110, 0.08);
}

.session-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  color: var(--muted);
  font-size: 0.88rem;
}

.session-detail {
  min-height: 260px;
  padding: 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.workflow-detail {
  min-height: 360px;
  padding: 20px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.78);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.empty-detail {
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--muted);
}

.step-list {
  display: grid;
  gap: 10px;
  margin-top: 18px;
}

.workflow-detail-grid,
.hint-grid,
.detail-stat-grid {
  display: grid;
  gap: 14px;
}

.detail-stat-grid {
  grid-template-columns: repeat(4, minmax(0, 1fr));
  margin-top: 16px;
}

.detail-stat {
  padding: 12px 14px;
  border-radius: var(--radius-sm);
  background: rgba(244, 239, 229, 0.66);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.detail-stat p {
  margin: 0;
}

.detail-stat .panel-label {
  margin-bottom: 8px;
}

.workflow-form {
  display: grid;
  gap: 16px;
  margin-top: 18px;
}

.workflow-form-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

.field-stack {
  display: grid;
  gap: 8px;
}

.field-stack label {
  font-size: 0.84rem;
  color: var(--muted);
}

.field-span-2 {
  grid-column: 1 / -1;
}

.feedback-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.button-secondary {
  background: rgba(29, 36, 31, 0.08);
  color: var(--text);
  box-shadow: none;
}

.button-danger {
  background: linear-gradient(135deg, #b45309, #9a3412);
  box-shadow: 0 10px 24px rgba(180, 83, 9, 0.2);
}

.button-subtle-danger {
  background: rgba(185, 28, 28, 0.1);
  color: var(--error);
  box-shadow: none;
}

.workflow-helper {
  margin: 0;
  color: var(--muted);
  line-height: 1.6;
}

.feedback-message {
  min-height: 1.2em;
  margin: 0;
  color: var(--accent);
  font-size: 0.9rem;
}

.hint-card {
  padding: 14px 16px;
  border-radius: var(--radius-sm);
  background: rgba(244, 239, 229, 0.66);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.hint-card h4 {
  margin: 0 0 8px;
  font-size: 0.98rem;
}

.hint-card p,
.hint-card ul {
  margin: 0;
  color: var(--muted);
  line-height: 1.55;
}

.hint-card ul {
  padding-left: 18px;
}

.step-card {
  padding: 12px 14px;
  border-radius: var(--radius-sm);
  background: rgba(244, 239, 229, 0.66);
  border: 1px solid rgba(29, 36, 31, 0.08);
}

.step-card p {
  margin: 0;
}

.step-card .step-meta {
  margin-top: 6px;
  color: var(--muted);
  font-size: 0.88rem;
}

.empty-state {
  padding: 18px;
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.74);
  border: 1px dashed rgba(29, 36, 31, 0.14);
  color: var(--muted);
  line-height: 1.6;
}

@media (max-width: 980px) {
  .hero,
  .command-bar,
  .status-panel,
  .summary-grid,
  .analysis-layout,
  .content-grid,
  .sessions-layout,
  .feedback-layout,
  .workflow-form-grid,
  .detail-stat-grid {
    grid-template-columns: 1fr;
  }

  .status-panel {
    display: grid;
  }

  .summary-grid {
    display: grid;
  }

  .hero {
    padding: 24px;
  }

  .command-bar {
    position: static;
  }
}
`;
}

export function renderViewerJs(): string {
  return `
const state = {
  window: "day",
  date: "",
  view: "overview",
  selectedSessionId: null,
  selectedWorkflowId: null,
  workflowActionMessage: "",
  analysisActionMessage: "",
  analysisApplyNames: false,
  analysisIncludeShortForm: false,
  analysisPollTimer: null,
  analysisRefreshing: false,
  latestDashboard: null,
  refreshTimer: null,
};

const viewerActionTokenMeta = document.querySelector('meta[name="wid-viewer-action-token"]');
const viewerActionToken = viewerActionTokenMeta
  ? viewerActionTokenMeta.getAttribute("content") || ""
  : "";

const elements = {
  windowSelect: document.getElementById("window-select"),
  dateInput: document.getElementById("date-input"),
  refreshButton: document.getElementById("refresh-button"),
  errorBanner: document.getElementById("error-banner"),
  agentStatus: document.getElementById("agent-status"),
  serverStatus: document.getElementById("server-status"),
  collectorStatus: document.getElementById("collector-status"),
  generatedAt: document.getElementById("generated-at"),
  summaryGrid: document.getElementById("summary-grid"),
  highlightsGrid: document.getElementById("highlights-grid"),
  snapshotList: document.getElementById("snapshot-list"),
  comparisonView: document.getElementById("comparison-view"),
  feedbackWorkflowList: document.getElementById("feedback-workflow-list"),
  workflowDetail: document.getElementById("workflow-detail"),
  workflowList: document.getElementById("workflow-list"),
  emergingWorkflowList: document.getElementById("emerging-workflow-list"),
  sessionList: document.getElementById("session-list"),
  sessionDetail: document.getElementById("session-detail"),
  analysisSurface: document.getElementById("analysis-surface"),
  analysisReadyList: document.getElementById("analysis-ready-list"),
  analysisResultsList: document.getElementById("analysis-results-list"),
  viewButtons: Array.from(document.querySelectorAll("[data-view-target]")),
  viewPanels: Array.from(document.querySelectorAll("[data-view-panel]")),
};

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function formatDateTime(value) {
  if (!value) {
    return "-";
  }

  return new Date(value).toLocaleString();
}

function formatDuration(seconds) {
  const rounded = Math.round(Number(seconds) || 0);
  const hours = Math.floor(rounded / 3600);
  const minutes = Math.floor((rounded % 3600) / 60);
  const remainingSeconds = rounded % 60;

  if (hours > 0) {
    return \`\${hours}h \${minutes}m\`;
  }

  if (minutes > 0) {
    return \`\${minutes}m \${remainingSeconds}s\`;
  }

  return \`\${remainingSeconds}s\`;
}

function formatSignedNumber(value) {
  const numeric = Number(value) || 0;

  return numeric > 0 ? \`+\${numeric}\` : String(numeric);
}

function formatSignedDuration(seconds) {
  const numeric = Number(seconds) || 0;

  if (numeric === 0) {
    return "0s";
  }

  return \`\${numeric > 0 ? "+" : "-"}\${formatDuration(Math.abs(numeric))}\`;
}

function toBooleanChoice(value) {
  if (value === true) {
    return "true";
  }

  if (value === false) {
    return "false";
  }

  return "";
}

function fromBooleanChoice(value) {
  if (value === "true") {
    return true;
  }

  if (value === "false") {
    return false;
  }

  return undefined;
}

function setWorkflowMessage(message) {
  state.workflowActionMessage = message || "";

  const element = document.getElementById("workflow-feedback-message");

  if (element) {
    element.textContent = state.workflowActionMessage;
  }
}

function buildWorkflowStatusChips(workflow) {
  const chips = [];

  chips.push('<span class="workflow-chip subtle">' + escapeHtml(workflow.visibleInReport ? "Visible in report" : "Removed from report") + "</span>");
  chips.push(
    '<span class="workflow-chip subtle">' +
      escapeHtml(workflow.detectionMode === "short_form" ? "Short form" : "Standard") +
      "</span>",
  );

  if (workflow.userLabeled) {
    chips.push('<span class="workflow-chip">Labeled</span>');
  }

  if (workflow.excluded) {
    chips.push('<span class="workflow-chip warn">Excluded</span>');
  }

  if (workflow.hidden) {
    chips.push('<span class="workflow-chip hidden-state">Hidden</span>');
  }

  if (workflow.approvedAutomationCandidate) {
    chips.push('<span class="workflow-chip">Approved candidate</span>');
  } else if (workflow.automationCandidate) {
    chips.push('<span class="workflow-chip subtle">Candidate review pending</span>');
  }

  return chips.join("");
}

function setError(message) {
  if (!message) {
    elements.errorBanner.textContent = "";
    elements.errorBanner.classList.add("hidden");
    return;
  }

  elements.errorBanner.textContent = message;
  elements.errorBanner.classList.remove("hidden");
}

function buildViewerActionHeaders() {
  return viewerActionToken
    ? {
        "X-What-Ive-Done-Viewer-Action-Token": viewerActionToken,
      }
    : {};
}

function clearAnalysisPoll() {
  if (state.analysisPollTimer) {
    window.clearTimeout(state.analysisPollTimer);
    state.analysisPollTimer = null;
  }
}

function scheduleAnalysisPoll() {
  clearAnalysisPoll();

  state.analysisPollTimer = window.setTimeout(() => {
    void refreshAnalysisPanel();
  }, 2000);
}

function buildQueryString() {
  const params = new URLSearchParams();
  params.set("window", state.window);
  params.set("view", state.view);

  if (state.date) {
    params.set("date", state.date);
  }

  if (state.analysisIncludeShortForm) {
    params.set("includeShortForm", "1");
  }

  return params.toString();
}

function syncUrl() {
  const url = new URL(window.location.href);
  url.search = buildQueryString();
  window.history.replaceState({}, "", url);
}

function initializeStateFromUrl() {
  const url = new URL(window.location.href);
  const selectedWindow = url.searchParams.get("window");
  const selectedDate = url.searchParams.get("date");
  const selectedView = url.searchParams.get("view");
  const includeShortForm = url.searchParams.get("includeShortForm");

  if (selectedWindow === "day" || selectedWindow === "week" || selectedWindow === "all") {
    state.window = selectedWindow;
  }

  if (selectedView === "overview" || selectedView === "review" || selectedView === "analysis") {
    state.view = selectedView;
  }

  if (selectedDate) {
    state.date = selectedDate;
  }

  if (includeShortForm === "1") {
    state.analysisIncludeShortForm = true;
  }

  elements.windowSelect.value = state.window;
  elements.dateInput.value = state.date;
}

function syncView() {
  for (const button of elements.viewButtons) {
    const viewTarget = button.getAttribute("data-view-target");
    const isActive = viewTarget === state.view;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", isActive ? "true" : "false");
  }

  for (const panel of elements.viewPanels) {
    const panelView = panel.getAttribute("data-view-panel");
    panel.classList.toggle("hidden", panelView !== state.view);
  }
}

function renderStatus(agentHealth, generatedAt) {
  elements.agentStatus.textContent = agentHealth.status;
  elements.agentStatus.className = "status-pill " + agentHealth.status;

  const ingestServer = agentHealth.runtime.state && agentHealth.runtime.state.ingestServer;
  elements.serverStatus.textContent =
    ingestServer && ingestServer.status === "running"
      ? \`\${ingestServer.host}:\${ingestServer.port}\`
      : ingestServer && ingestServer.status
        ? ingestServer.status
        : "stopped";

  const collectors = agentHealth.collectors || [];

  if (collectors.length === 0) {
    elements.collectorStatus.textContent = "No collectors";
  } else {
    elements.collectorStatus.textContent = collectors.map((collector) => {
      return \`\${collector.id} (\${collector.status})\`;
    }).join(", ");
  }

  elements.generatedAt.textContent = formatDateTime(generatedAt);
}

function renderSummaryCards(data) {
  const cards = [
    {
      label: "Tracked Sessions",
      value: data.report.totalSessions,
      note: \`\${data.sessionSummaries.length} sessions listed in this live view\`,
    },
    {
      label: "Tracked Time",
      value: formatDuration(data.report.totalTrackedDurationSeconds),
      note: \`Window: \${data.timeWindow.window} on \${data.timeWindow.reportDate}\`,
    },
    {
      label: "Confirmed Workflows",
      value: data.report.workflows.length,
      note: "Repeated workflows above the current threshold",
    },
    {
      label: "Emerging Workflows",
      value: data.report.emergingWorkflows.length,
      note: "Early patterns that still need more repetition",
    },
    {
      label: "Raw Events",
      value: data.rawEventCount,
      note: data.latestEventAt ? \`Latest event at \${formatDateTime(data.latestEventAt)}\` : "No raw events yet",
    },
  ];

  elements.summaryGrid.innerHTML = cards.map((card) => {
    return \`
      <article class="summary-card">
        <p class="panel-label">\${escapeHtml(card.label)}</p>
        <p class="value">\${escapeHtml(card.value)}</p>
        <p class="note">\${escapeHtml(card.note)}</p>
      </article>
    \`;
  }).join("");
}

function highlightMarkup(title, entries, formatter) {
  if (!entries || entries.length === 0) {
    return \`
      <article class="highlight-card">
        <h3>\${escapeHtml(title)}</h3>
        <p>No items yet in this window.</p>
      </article>
    \`;
  }

  return \`
    <article class="highlight-card">
      <h3>\${escapeHtml(title)}</h3>
      \${entries.map((entry) => {
        return \`<p><strong>\${escapeHtml(entry.workflowName)}</strong> \${escapeHtml(formatter(entry))}</p>\`;
      }).join("")}
    </article>
  \`;
}

function renderHighlights(summary) {
  elements.highlightsGrid.innerHTML = [
    highlightMarkup("Top Repetitive", summary.topRepetitiveWorkflows, (entry) => {
      return \`\${entry.frequency} repeats, \${formatDuration(entry.totalDurationSeconds)} total\`;
    }),
    highlightMarkup("Time-Heavy", summary.highestTimeConsumingRepetitiveWorkflows, (entry) => {
      return \`\${formatDuration(entry.totalDurationSeconds)} total, \${entry.frequency} repeats\`;
    }),
    highlightMarkup("Quick Wins", summary.quickWinAutomationCandidates, (entry) => {
      return \`\${entry.automationSuitability} automation fit, confidence \${entry.confidenceScore}\`;
    }),
    highlightMarkup("Needs Review", summary.workflowsNeedingHumanJudgment, (entry) => {
      return \`confidence \${entry.confidenceScore}, labeled: \${entry.userLabeled ? "yes" : "no"}\`;
    }),
  ].join("");
}

function renderSnapshotList(snapshots) {
  if (!snapshots || snapshots.length === 0) {
    elements.snapshotList.innerHTML = '<div class="empty-state">No stored snapshots yet.</div>';
    return;
  }

  elements.snapshotList.innerHTML = snapshots.map((snapshot) => {
    return \`
      <article class="snapshot-card">
        <h3>\${escapeHtml(snapshot.window.toUpperCase())} snapshot</h3>
        <p>\${escapeHtml(snapshot.reportDate)} in \${escapeHtml(snapshot.timezone)}</p>
        <p>\${escapeHtml(String(snapshot.totalSessions))} sessions, \${escapeHtml(String(snapshot.workflowCount))} confirmed workflows, \${escapeHtml(String(snapshot.emergingWorkflowCount))} emerging</p>
        <p class="muted">Generated \${escapeHtml(formatDateTime(snapshot.generatedAt))}</p>
      </article>
    \`;
  }).join("");
}

function renderComparisonEntries(entries, emptyMessage) {
  if (!entries || entries.length === 0) {
    return \`<div class="empty-state">\${escapeHtml(emptyMessage)}</div>\`;
  }

  return \`
    <div class="comparison-entry-list">
      \${entries.map((entry) => {
        const previousName = entry.previousWorkflowName
          ? \`<p class="muted">Previously: \${escapeHtml(entry.previousWorkflowName)}</p>\`
          : "";

        return \`
          <article class="comparison-entry">
            <strong>\${escapeHtml(entry.workflowName)}</strong>
            \${previousName}
            <p class="muted">
              repeats \${escapeHtml(formatSignedNumber(entry.frequencyDelta))} |
              time \${escapeHtml(formatSignedDuration(entry.totalDurationDeltaSeconds))}
            </p>
          </article>
        \`;
      }).join("")}
    </div>
  \`;
}

function renderComparisonView(comparison) {
  if (!comparison) {
    elements.comparisonView.innerHTML =
      '<div class="empty-state">Comparison is available only for day and week windows.</div>';
    return;
  }

  const summaryCards = [
    {
      label: "Compared Against",
      value: comparison.previousTimeWindow.reportDate,
      note: \`\${comparison.previousTimeWindow.window} window in \${comparison.previousTimeWindow.timezone}\`,
    },
    {
      label: "Sessions Delta",
      value: formatSignedNumber(comparison.summary.sessionDelta),
      note: "Current window sessions minus previous window sessions",
    },
    {
      label: "Tracked Time Delta",
      value: formatSignedDuration(comparison.summary.trackedDurationDeltaSeconds),
      note: "Change in total tracked time across matching windows",
    },
    {
      label: "Approved Candidate Time",
      value: formatSignedDuration(comparison.summary.approvedCandidateTimeDeltaSeconds),
      note: "Shift in time spent on approved automation candidates",
    },
  ];

  elements.comparisonView.innerHTML = \`
    <div class="comparison-summary-grid">
      \${summaryCards.map((card) => {
        return \`
          <article class="comparison-summary-card">
            <p class="panel-label">\${escapeHtml(card.label)}</p>
            <p class="value">\${escapeHtml(card.value)}</p>
            <p class="note">\${escapeHtml(card.note)}</p>
          </article>
        \`;
      }).join("")}
    </div>
    <div class="comparison-columns">
      <section class="comparison-column">
        <p class="panel-label">Newly Appeared</p>
        <h3>Confirmed workflows that were not present before</h3>
        \${renderComparisonEntries(
          comparison.newlyAppearedWorkflows,
          "No newly appeared confirmed workflows in this comparison window.",
        )}
      </section>
      <section class="comparison-column">
        <p class="panel-label">Disappeared</p>
        <h3>Confirmed workflows that dropped out of the previous set</h3>
        \${renderComparisonEntries(
          comparison.disappearedWorkflows,
          "No confirmed workflows disappeared in this comparison window.",
        )}
      </section>
      <section class="comparison-column">
        <p class="panel-label">Automation Effect</p>
        <h3>Approved candidate workflows with time shifts</h3>
        \${renderComparisonEntries(
          comparison.approvedCandidateChanges,
          "No approved automation candidate changes yet.",
        )}
      </section>
    </div>
  \`;
}

function renderFeedbackWorkflowList(workflows) {
  if (!workflows || workflows.length === 0) {
    state.selectedWorkflowId = null;
    elements.feedbackWorkflowList.innerHTML = '<div class="empty-state">No confirmed workflows are available for review in this window yet.</div>';
    elements.workflowDetail.textContent = 'Select a workflow to review its current label, visibility state, and automation hints.';
    elements.workflowDetail.className = 'workflow-detail empty-detail';
    return;
  }

  if (!state.selectedWorkflowId || !workflows.some((workflow) => workflow.id === state.selectedWorkflowId)) {
    state.selectedWorkflowId = workflows[0].id;
  }

  elements.feedbackWorkflowList.innerHTML = workflows.map((workflow) => {
    const isActive = workflow.id === state.selectedWorkflowId;

    return \`
      <button class="workflow-review-button \${isActive ? "active" : ""}" type="button" data-workflow-id="\${escapeHtml(workflow.id)}">
        <div class="workflow-review-header">
          <div>
            <strong>\${escapeHtml(workflow.workflowName)}</strong>
            <div class="workflow-review-meta">
              <span>\${escapeHtml(String(workflow.frequency))} repeats</span>
              <span>\${escapeHtml(formatDuration(workflow.totalDurationSeconds))} total</span>
              <span>confidence \${escapeHtml(String(workflow.confidenceScore))}</span>
            </div>
          </div>
        </div>
        <div class="workflow-chip-row">
          \${buildWorkflowStatusChips(workflow)}
        </div>
      </button>
    \`;
  }).join("");

  for (const button of elements.feedbackWorkflowList.querySelectorAll("[data-workflow-id]")) {
    button.addEventListener("click", () => {
      state.selectedWorkflowId = button.getAttribute("data-workflow-id");
      state.workflowActionMessage = "";
      renderFeedbackWorkflowList(workflows);
      void refreshWorkflowDetail();
    });
  }
}

function renderWorkflowTable(container, workflows, emptyMessage, isEmerging = false) {
  if (!workflows || workflows.length === 0) {
    container.innerHTML = \`<div class="empty-state">\${escapeHtml(emptyMessage)}</div>\`;
    return;
  }

  const rows = workflows.map((workflow) => {
    const previewSteps = workflow.representativeSteps.slice(0, isEmerging ? 4 : 5);
    const remainingStepCount = Math.max(0, workflow.representativeSteps.length - previewSteps.length);
    const recommendation = isEmerging ? "Needs more repeated sessions" : workflow.recommendedApproach;
    const score = isEmerging ? workflow.confidence : workflow.confidenceScore;
    const timeSpent = isEmerging ? workflow.totalDurationSeconds : workflow.totalDurationSeconds;

    return \`
      <tr>
        <td>
          <strong>\${escapeHtml(workflow.workflowName)}</strong>
          \${!isEmerging
            ? \`<div class="workflow-chip-row"><span class="workflow-chip subtle">\${escapeHtml(
                workflow.detectionMode === "short_form" ? "Short form" : "Standard",
              )}</span></div>\`
            : ""}
          <div class="step-preview">
            \${previewSteps.map((step) => \`<span class="step-pill">\${escapeHtml(step)}</span>\`).join("")}
            \${remainingStepCount > 0 ? \`<span class="step-pill more">+\${escapeHtml(String(remainingStepCount))} more</span>\` : ""}
          </div>
        </td>
        <td>\${escapeHtml(String(workflow.frequency))}</td>
        <td>\${escapeHtml(formatDuration(workflow.averageDurationSeconds))}</td>
        <td>\${escapeHtml(formatDuration(timeSpent))}</td>
        <td>\${escapeHtml(String(score))}</td>
        <td>\${escapeHtml(recommendation)}</td>
      </tr>
    \`;
  }).join("");

  container.innerHTML = \`
    <table>
      <thead>
        <tr>
          <th>Workflow</th>
          <th>Frequency</th>
          <th>Avg Duration</th>
          <th>Total Time</th>
          <th>\${isEmerging ? "State" : "Confidence"}</th>
          <th>\${isEmerging ? "Why" : "Recommendation"}</th>
        </tr>
      </thead>
      <tbody>\${rows}</tbody>
    </table>
  \`;
}

function renderAnalysisReadyList(workflows) {
  if (!workflows || workflows.length === 0) {
    elements.analysisReadyList.innerHTML =
      '<div class="empty-state">No confirmed workflows are ready for interpretation in this window yet.</div>';
    return;
  }

  elements.analysisReadyList.innerHTML = workflows.slice(0, 6).map((workflow) => {
    return \`
      <article class="analysis-ready-card">
        <div>
          <p class="panel-label">Analysis Candidate</p>
          <h3>\${escapeHtml(workflow.workflowName)}</h3>
        </div>
        <div class="analysis-meta">
          <span class="workflow-chip subtle">\${escapeHtml(
            workflow.detectionMode === "short_form" ? "short form" : "standard",
          )}</span>
          <span class="workflow-chip subtle">\${escapeHtml(String(workflow.frequency))} repeats</span>
          <span class="workflow-chip subtle">\${escapeHtml(formatDuration(workflow.totalDurationSeconds))} total</span>
          <span class="workflow-chip subtle">confidence \${escapeHtml(String(workflow.confidenceScore))}</span>
        </div>
        <div class="step-preview">
          \${(workflow.representativeSteps || [])
            .slice(0, 4)
            .map((step) => \`<span class="step-pill">\${escapeHtml(step)}</span>\`)
            .join("")}
        </div>
        <p class="analysis-copy">\${escapeHtml(workflow.recommendedApproach || "Pending automation guidance")}</p>
      </article>
    \`;
  }).join("");
}

function renderAnalysisResults(analyses, latestRun) {
  if (!analyses || analyses.length === 0) {
    const emptyMessage =
      latestRun && latestRun.status === "failed"
        ? latestRun.summary && latestRun.summary.error
          ? latestRun.summary.error
          : "The last analysis run failed before it could store workflow interpretations."
        : "No stored analysis results yet. Start a manual run from this tab.";

    elements.analysisResultsList.innerHTML = \`<div class="empty-state">\${escapeHtml(emptyMessage)}</div>\`;
    return;
  }

  elements.analysisResultsList.innerHTML = analyses.slice(0, 8).map((analysis) => {
    return \`
      <article class="analysis-result-card">
        <div>
          <p class="panel-label">Workflow Interpretation</p>
          <h3>\${escapeHtml(analysis.workflowName)}</h3>
        </div>
        <p class="analysis-result-summary">\${escapeHtml(analysis.workflowSummary)}</p>
        <div class="analysis-meta">
          <span class="workflow-chip subtle">\${escapeHtml(analysis.provider)}</span>
          <span class="workflow-chip subtle">\${escapeHtml(analysis.model)}</span>
          <span class="workflow-chip">\${escapeHtml(analysis.automationSuitability)} fit</span>
        </div>
        <p class="analysis-copy">\${escapeHtml(analysis.recommendedApproach)}</p>
        <p class="analysis-result-summary">\${escapeHtml(analysis.rationale)}</p>
      </article>
    \`;
  }).join("");
}

function renderAnalysisSurface(dashboardData, statusData, resultsData) {
  const selectedProvider = (statusData.credentialStatus.providers || []).find((provider) => provider.selected);
  const currentModel =
    (statusData.credentialStatus.configuration && statusData.credentialStatus.configuration.model) ||
    (selectedProvider ? selectedProvider.defaultModel : "default");
  const credentialReady = selectedProvider
    ? selectedProvider.hasApiKey || selectedProvider.hasOAuthCredentials || selectedProvider.envApiKeyAvailable
    : false;
  const latestRun = statusData.latestRun || resultsData.latestRun || null;
  const latestResultCount = Array.isArray(resultsData.analyses)
    ? resultsData.analyses.length
    : statusData.latestResultCount || 0;
  const runDisabled = statusData.running || statusData.payloadCount === 0;
  const runButtonLabel = statusData.running
    ? "Running..."
    : statusData.payloadCount === 0
      ? "Nothing To Analyze"
      : "Run Analysis";
  const latestRunCopy = !latestRun
    ? "No manual analysis run has been started from the viewer yet."
    : latestRun.status === "running"
      ? "The local console has sent summarized workflow payloads and is waiting for the provider response."
      : latestRun.status === "failed"
        ? latestRun.summary && latestRun.summary.error
          ? latestRun.summary.error
          : "The latest analysis run failed."
        : "Stored interpretation results are available below and will stay visible after refresh.";
  const credentialCopy = !selectedProvider
    ? "No provider is selected in the saved CLI configuration."
    : credentialReady
      ? "Viewer analysis can use the same provider configuration that is already available to the CLI."
      : "The selected provider is missing credentials. Configure auth from the CLI before starting a viewer run.";

  elements.analysisSurface.innerHTML = \`
    <article class="analysis-card accent">
      <div>
        <p class="panel-label">Run Manual Analysis</p>
        <h3>\${escapeHtml(dashboardData.timeWindow.reportDate)}</h3>
      </div>
      <p class="analysis-copy">
        Send only summarized workflow payloads for the current \${escapeHtml(dashboardData.timeWindow.window)} window. Raw events, raw URLs, and window titles stay local.
      </p>
      <div class="analysis-meta">
        <span class="workflow-chip">\${escapeHtml(String(statusData.workflowCount))} confirmed workflows</span>
        <span class="workflow-chip subtle">\${escapeHtml(String(statusData.payloadCount))} summarized payloads</span>
        \${!statusData.includeShortForm && statusData.shortFormExcludedCount > 0
          ? \`<span class="workflow-chip subtle">\${escapeHtml(String(statusData.shortFormExcludedCount))} short-form excluded by default</span>\`
          : statusData.includeShortForm
            ? '<span class="workflow-chip subtle">Short-form included</span>'
            : ""}
      </div>
      <div class="analysis-action-row">
        <button id="analysis-run-button" class="\${runDisabled ? "button-secondary" : ""}" type="button" \${runDisabled ? "disabled" : ""}>\${escapeHtml(runButtonLabel)}</button>
        <label class="analysis-toggle" for="analysis-apply-names">
          <input id="analysis-apply-names" type="checkbox" \${state.analysisApplyNames ? "checked" : ""} />
          <span>Apply suggested names</span>
        </label>
        <label class="analysis-toggle" for="analysis-include-short-form">
          <input id="analysis-include-short-form" type="checkbox" \${state.analysisIncludeShortForm ? "checked" : ""} />
          <span>Include short-form workflows</span>
        </label>
      </div>
      <p class="analysis-status-copy">\${escapeHtml(state.analysisActionMessage || latestRunCopy)}</p>
    </article>
    <article class="analysis-card">
      <div>
        <p class="panel-label">Provider Status</p>
        <h3>\${escapeHtml(selectedProvider ? selectedProvider.label : "Not configured")}</h3>
      </div>
      <p class="analysis-copy">\${escapeHtml(credentialCopy)}</p>
      <div class="analysis-meta">
        <span class="workflow-chip subtle">\${escapeHtml(currentModel)}</span>
        <span class="workflow-chip subtle">\${escapeHtml(
          statusData.credentialStatus.configuration && statusData.credentialStatus.configuration.authMethod
            ? statusData.credentialStatus.configuration.authMethod
            : "unknown auth",
        )}</span>
        <span class="workflow-chip subtle">\${escapeHtml(statusData.credentialStatus.backend || "unknown backend")}</span>
      </div>
      \${statusData.credentialStatus.warning
        ? \`<p class="analysis-status-copy">\${escapeHtml(statusData.credentialStatus.warning)}</p>\`
        : ""}
    </article>
    <article class="analysis-card">
      <div>
        <p class="panel-label">Latest Run</p>
        <h3>\${escapeHtml(latestRun ? latestRun.status : "idle")}</h3>
      </div>
      <p class="analysis-copy">\${escapeHtml(latestRunCopy)}</p>
      <div class="analysis-meta">
        <span class="workflow-chip subtle">\${escapeHtml(String(latestResultCount))} results</span>
        <span class="workflow-chip subtle">\${escapeHtml(formatDateTime(latestRun ? latestRun.startedAt : undefined))} started</span>
        \${latestRun && latestRun.completedAt
          ? \`<span class="workflow-chip subtle">\${escapeHtml(formatDateTime(latestRun.completedAt))} finished</span>\`
          : ""}
      </div>
    </article>
    <article class="analysis-note">
      <p>Only summarized workflow payloads leave the machine during manual analysis.</p>
      <div class="workflow-chip-row">
        <span class="workflow-chip subtle">No raw event dump</span>
        <span class="workflow-chip subtle">No raw URLs or window titles</span>
        <span class="workflow-chip subtle">No content fields</span>
      </div>
    </article>
  \`;

  const applyNamesToggle = document.getElementById("analysis-apply-names");
  const includeShortFormToggle = document.getElementById("analysis-include-short-form");
  const runButton = document.getElementById("analysis-run-button");

  if (applyNamesToggle) {
    applyNamesToggle.addEventListener("change", () => {
      state.analysisApplyNames = Boolean(applyNamesToggle.checked);
    });
  }

  if (includeShortFormToggle) {
    includeShortFormToggle.addEventListener("change", () => {
      state.analysisIncludeShortForm = Boolean(includeShortFormToggle.checked);
      syncUrl();
      void refreshAnalysisPanel();
    });
  }

  if (runButton) {
    runButton.addEventListener("click", () => {
      void submitAnalysisRun().catch((error) => {
        state.analysisActionMessage =
          error instanceof Error ? error.message : "Unknown viewer analysis error";
        void refreshAnalysisPanel();
      });
    });
  }
}

async function submitAnalysisRun() {
  state.analysisActionMessage = "Starting analysis...";
  await refreshAnalysisPanel();

  const response = await fetch(\`/api/viewer/analysis/runs?\${buildQueryString()}\`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...buildViewerActionHeaders(),
    },
    body: JSON.stringify({
      applyNames: state.analysisApplyNames,
      includeShortForm: state.analysisIncludeShortForm,
    }),
  });

  if (!response.ok) {
    const errorPayload = await response.json().catch(() => null);
    throw new Error(errorPayload && errorPayload.message ? errorPayload.message : "Failed to start viewer analysis.");
  }

  state.analysisActionMessage = "Analysis run started.";
  await refreshAnalysisPanel();
}

async function refreshAnalysisPanel(dashboardData = state.latestDashboard) {
  if (!dashboardData || state.analysisRefreshing) {
    return;
  }

  state.analysisRefreshing = true;

  try {
    const [statusResponse, resultsResponse] = await Promise.all([
      fetch(\`/api/viewer/analysis/status?\${buildQueryString()}\`),
      fetch("/api/viewer/analysis/results"),
    ]);

    if (!statusResponse.ok) {
      throw new Error("Failed to load analysis status.");
    }

    if (!resultsResponse.ok) {
      throw new Error("Failed to load analysis results.");
    }

    const statusData = await statusResponse.json();
    const resultsData = await resultsResponse.json();
    const latestRun = resultsData.latestRun || statusData.latestRun || null;
    const quickWins =
      dashboardData.report.summary && dashboardData.report.summary.quickWinAutomationCandidates
        ? dashboardData.report.summary.quickWinAutomationCandidates
        : [];
    const analysisReadyWorkflows = (quickWins.length > 0 ? quickWins : dashboardData.report.workflows).filter(
      (workflow) => state.analysisIncludeShortForm || workflow.detectionMode !== "short_form",
    );

    if (!statusData.running && latestRun && latestRun.status === "completed" && state.analysisActionMessage === "Analysis run started.") {
      state.analysisActionMessage = "Analysis run completed.";
    }

    if (!statusData.running && latestRun && latestRun.status === "failed" && state.analysisActionMessage === "Analysis run started.") {
      state.analysisActionMessage =
        latestRun.summary && latestRun.summary.error
          ? latestRun.summary.error
          : "Analysis run failed.";
    }

    renderAnalysisReadyList(analysisReadyWorkflows);
    renderAnalysisSurface(dashboardData, statusData, resultsData);
    renderAnalysisResults(resultsData.analyses, latestRun);

    if (statusData.running || (statusData.latestRun && statusData.latestRun.status === "running")) {
      scheduleAnalysisPoll();
    } else {
      clearAnalysisPoll();
    }
  } catch (error) {
    clearAnalysisPoll();
    elements.analysisSurface.innerHTML = \`<div class="empty-state">\${escapeHtml(error instanceof Error ? error.message : "Unknown viewer analysis error")}</div>\`;
    elements.analysisResultsList.innerHTML =
      '<div class="empty-state">Analysis results are unavailable right now.</div>';
  } finally {
    state.analysisRefreshing = false;
  }
}

function renderEmergingWorkflowList(container, workflows, emptyMessage) {
  if (!workflows || workflows.length === 0) {
    container.innerHTML = \`<div class="empty-state">\${escapeHtml(emptyMessage)}</div>\`;
    return;
  }

  container.innerHTML = \`
    <div class="emerging-grid">
      \${workflows.map((workflow) => {
        const previewSteps = workflow.representativeSteps.slice(0, 4);
        const remainingCount = Math.max(0, workflow.representativeSteps.length - previewSteps.length);

        return \`
          <details class="emerging-card">
            <summary class="emerging-summary">
              <div class="emerging-summary-top">
                <div>
                  <h3>\${escapeHtml(workflow.workflowName)}</h3>
                  <div class="emerging-meta">
                    <span class="emerging-stat">\${escapeHtml(String(workflow.frequency))} repeat</span>
                    <span class="emerging-stat">avg \${escapeHtml(formatDuration(workflow.averageDurationSeconds))}</span>
                    <span class="emerging-stat">total \${escapeHtml(formatDuration(workflow.totalDurationSeconds))}</span>
                    <span class="emerging-stat">\${escapeHtml(workflow.confidence)}</span>
                  </div>
                </div>
                <span class="emerging-toggle">Show steps</span>
              </div>
              <div class="emerging-preview">
                \${previewSteps.map((step) => \`<span class="step-pill">\${escapeHtml(step)}</span>\`).join("")}
                \${remainingCount > 0 ? \`<span class="step-pill more">+\${escapeHtml(String(remainingCount))} more</span>\` : ""}
              </div>
            </summary>
            <div class="emerging-body">
              <p class="emerging-body-copy">
                This pattern is still provisional. It becomes a confirmed workflow after more repeated sessions.
              </p>
              <div class="emerging-step-list">
                \${workflow.representativeSteps.map((step, index) => {
                  return \`
                    <div class="emerging-step">
                      <span class="emerging-step-index">\${escapeHtml(String(index + 1))}</span>
                      <div class="emerging-step-card">
                        <p>\${escapeHtml(step)}</p>
                      </div>
                    </div>
                  \`;
                }).join("")}
              </div>
            </div>
          </details>
        \`;
      }).join("")}
    </div>
  \`;
}

async function submitWorkflowFeedback(payload, successMessage) {
  if (!state.selectedWorkflowId) {
    return;
  }

  setWorkflowMessage("Saving feedback...");

  const response = await fetch(\`/api/viewer/workflows/\${encodeURIComponent(state.selectedWorkflowId)}?\${buildQueryString()}\`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...buildViewerActionHeaders(),
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorPayload = await response.json().catch(() => null);
    throw new Error(errorPayload && errorPayload.message ? errorPayload.message : "Failed to save workflow feedback.");
  }

  state.workflowActionMessage = successMessage;
  await refreshDashboard();
}

function renderAutomationHints(hints) {
  if (!hints || hints.length === 0) {
    return '<div class="empty-state">No automation hints have been generated for this workflow yet.</div>';
  }

  return \`
    <div class="hint-grid">
      \${hints.map((hint) => {
        return \`
          <article class="hint-card">
            <h4>\${escapeHtml(hint.suggestedApproach)}</h4>
            <p>\${escapeHtml(hint.whyThisFits)}</p>
            <div class="workflow-chip-row">
              <span class="workflow-chip">\${escapeHtml(hint.estimatedDifficulty)} difficulty</span>
              <span class="workflow-chip subtle">\${escapeHtml(hint.expectedTimeSavings)}</span>
            </div>
            <ul>
              \${(hint.prerequisites || []).map((item) => \`<li>\${escapeHtml(item)}</li>\`).join("")}
            </ul>
          </article>
        \`;
      }).join("")}
    </div>
  \`;
}

function renderWorkflowDetail(workflow) {
  elements.workflowDetail.className = "workflow-detail";
  elements.workflowDetail.innerHTML = \`
    <div class="workflow-detail-grid">
      <div>
        <p class="panel-label">Workflow Review</p>
        <h3>\${escapeHtml(workflow.workflowName)}</h3>
        <p class="workflow-helper">
          \${escapeHtml(workflow.businessPurpose || workflow.recommendedApproach)}
        </p>
        <div class="workflow-chip-row">
          \${buildWorkflowStatusChips(workflow)}
          <span class="workflow-chip subtle">\${escapeHtml(workflow.automationSuitability)} automation fit</span>
        </div>
      </div>

      <div class="detail-stat-grid">
        <article class="detail-stat">
          <p class="panel-label">Frequency</p>
          <p>\${escapeHtml(String(workflow.frequency))}</p>
        </article>
        <article class="detail-stat">
          <p class="panel-label">Average</p>
          <p>\${escapeHtml(formatDuration(workflow.averageDurationSeconds))}</p>
        </article>
        <article class="detail-stat">
          <p class="panel-label">Total</p>
          <p>\${escapeHtml(formatDuration(workflow.totalDurationSeconds))}</p>
        </article>
        <article class="detail-stat">
          <p class="panel-label">Confidence</p>
          <p>\${escapeHtml(String(workflow.confidenceScore))}</p>
        </article>
      </div>

      <div>
        <p class="panel-label">Representative Steps</p>
        <div class="step-preview">
          \${workflow.representativeSteps.map((step) => \`<span class="step-pill">\${escapeHtml(step)}</span>\`).join("")}
        </div>
      </div>

      <div>
        <p class="panel-label">Structured Automation Hints</p>
        \${renderAutomationHints(workflow.automationHints)}
      </div>

      <form id="workflow-review-form" class="workflow-form">
        <div class="workflow-form-grid">
          <div class="field-stack">
            <label for="workflow-name-input">Display Name</label>
            <input id="workflow-name-input" name="name" type="text" value="\${escapeHtml(workflow.workflowName)}" />
          </div>
          <div class="field-stack">
            <label for="workflow-purpose-input">Business Purpose</label>
            <textarea id="workflow-purpose-input" name="purpose">\${escapeHtml(workflow.businessPurpose || "")}</textarea>
          </div>
          <div class="field-stack">
            <label for="workflow-repetitive-select">Repetitive</label>
            <select id="workflow-repetitive-select" name="repetitive">
              <option value="" \${workflow.repetitive === undefined ? "selected" : ""}>Keep current</option>
              <option value="true" \${workflow.repetitive === true ? "selected" : ""}>Yes</option>
              <option value="false" \${workflow.repetitive === false ? "selected" : ""}>No</option>
            </select>
          </div>
          <div class="field-stack">
            <label for="workflow-candidate-select">Automation Candidate</label>
            <select id="workflow-candidate-select" name="automationCandidate">
              <option value="" \${workflow.automationCandidate === undefined ? "selected" : ""}>Keep current</option>
              <option value="true" \${workflow.automationCandidate === true ? "selected" : ""}>Yes</option>
              <option value="false" \${workflow.automationCandidate === false ? "selected" : ""}>No</option>
            </select>
          </div>
          <div class="field-stack">
            <label for="workflow-difficulty-select">Difficulty</label>
            <select id="workflow-difficulty-select" name="difficulty">
              <option value="" \${!workflow.automationDifficulty ? "selected" : ""}>Keep current</option>
              <option value="low" \${workflow.automationDifficulty === "low" ? "selected" : ""}>Low</option>
              <option value="medium" \${workflow.automationDifficulty === "medium" ? "selected" : ""}>Medium</option>
              <option value="high" \${workflow.automationDifficulty === "high" ? "selected" : ""}>High</option>
            </select>
          </div>
          <div class="field-stack">
            <label for="workflow-approved-select">Approved Candidate</label>
            <select id="workflow-approved-select" name="approvedAutomationCandidate">
              <option value="" \${workflow.approvedAutomationCandidate === undefined ? "selected" : ""}>Keep current</option>
              <option value="true" \${workflow.approvedAutomationCandidate === true ? "selected" : ""}>Yes</option>
              <option value="false" \${workflow.approvedAutomationCandidate === false ? "selected" : ""}>No</option>
            </select>
          </div>
        </div>

        <div class="feedback-actions">
          <button id="workflow-save-button" type="submit">Save Review</button>
          <button id="workflow-exclude-button" class="button-secondary" type="button">\${workflow.excluded ? "Include in Report" : "Exclude from Report"}</button>
          <button id="workflow-hide-button" class="\${workflow.hidden ? "button-secondary" : "button-subtle-danger"}" type="button">\${workflow.hidden ? "Show Workflow" : "Hide Workflow"}</button>
        </div>
        <p id="workflow-feedback-message" class="feedback-message">\${escapeHtml(state.workflowActionMessage)}</p>
      </form>
    </div>
  \`;

  const form = document.getElementById("workflow-review-form");
  const excludeButton = document.getElementById("workflow-exclude-button");
  const hideButton = document.getElementById("workflow-hide-button");

  form.addEventListener("submit", (event) => {
    event.preventDefault();

    const formData = new FormData(form);
    const name = String(formData.get("name") || "").trim();
    const purpose = String(formData.get("purpose") || "").trim();

    void submitWorkflowFeedback(
      {
        name: name || undefined,
        purpose: purpose || undefined,
        repetitive: fromBooleanChoice(String(formData.get("repetitive") || "")),
        automationCandidate: fromBooleanChoice(String(formData.get("automationCandidate") || "")),
        difficulty: String(formData.get("difficulty") || "") || undefined,
        approvedAutomationCandidate: fromBooleanChoice(
          String(formData.get("approvedAutomationCandidate") || ""),
        ),
      },
      "Workflow review saved.",
    ).catch((error) => {
      setWorkflowMessage(error instanceof Error ? error.message : "Unknown workflow feedback error");
    });
  });

  excludeButton.addEventListener("click", () => {
    void submitWorkflowFeedback(
      {
        excluded: !workflow.excluded,
      },
      workflow.excluded ? "Workflow returned to report." : "Workflow excluded from report.",
    ).catch((error) => {
      setWorkflowMessage(error instanceof Error ? error.message : "Unknown workflow feedback error");
    });
  });

  hideButton.addEventListener("click", () => {
    void submitWorkflowFeedback(
      {
        hidden: !workflow.hidden,
      },
      workflow.hidden ? "Workflow is visible again." : "Workflow hidden from review lists.",
    ).catch((error) => {
      setWorkflowMessage(error instanceof Error ? error.message : "Unknown workflow feedback error");
    });
  });
}

async function refreshWorkflowDetail() {
  if (!state.selectedWorkflowId) {
    elements.workflowDetail.textContent = 'Select a workflow to review its current label, visibility state, and automation hints.';
    elements.workflowDetail.className = 'workflow-detail empty-detail';
    return;
  }

  const response = await fetch(\`/api/viewer/workflows/\${encodeURIComponent(state.selectedWorkflowId)}?\${buildQueryString()}\`);

  if (!response.ok) {
    throw new Error("Failed to load workflow detail.");
  }

  const workflow = await response.json();
  renderWorkflowDetail(workflow);
}

function renderSessionList(sessions) {
  if (!sessions || sessions.length === 0) {
    state.selectedSessionId = null;
    elements.sessionList.innerHTML = '<div class="empty-state">No sessions detected for this window yet.</div>';
    elements.sessionDetail.textContent = 'Select a session to inspect the ordered steps.';
    elements.sessionDetail.className = 'session-detail empty-detail';
    return;
  }

  if (!state.selectedSessionId || !sessions.some((session) => session.id === state.selectedSessionId)) {
    state.selectedSessionId = sessions[0].id;
  }

  elements.sessionList.innerHTML = sessions.map((session) => {
    const isActive = session.id === state.selectedSessionId;

    return \`
      <button class="session-button \${isActive ? "active" : ""}" type="button" data-session-id="\${escapeHtml(session.id)}">
        <strong>\${escapeHtml(session.primaryApplication)}</strong>
        <span class="session-meta">
          <span>\${escapeHtml(session.primaryDomain || "No domain")}</span>
          <span>\${escapeHtml(formatDuration(session.durationSeconds))}</span>
          <span>\${escapeHtml(String(session.stepCount))} steps</span>
        </span>
        <span class="muted">\${escapeHtml(formatDateTime(session.startTime))}</span>
      </button>
    \`;
  }).join("");

  for (const button of elements.sessionList.querySelectorAll("[data-session-id]")) {
    button.addEventListener("click", () => {
      state.selectedSessionId = button.getAttribute("data-session-id");
      renderSessionList(sessions);
      void refreshSessionDetail();
    });
  }
}

async function refreshSessionDetail() {
  if (!state.selectedSessionId) {
    elements.sessionDetail.textContent = 'Select a session to inspect the ordered steps.';
    elements.sessionDetail.className = 'session-detail empty-detail';
    return;
  }

  const response = await fetch(\`/api/viewer/sessions/\${encodeURIComponent(state.selectedSessionId)}?\${buildQueryString()}\`);

  if (!response.ok) {
    throw new Error('Failed to load session detail.');
  }

  const session = await response.json();
  const steps = (session.steps || []).map((step) => {
    const target = step.target ? \` -> \${step.target}\` : "";
    const context = [step.domain, step.titlePattern].filter(Boolean).join(" | ");

    return \`
      <article class="step-card">
        <p><strong>\${escapeHtml(String(step.order))}. \${escapeHtml(step.actionName || step.action)}</strong></p>
        <p class="step-meta">\${escapeHtml(formatDateTime(step.timestamp))} | \${escapeHtml(step.application)}\${target ? " | " + escapeHtml(target) : ""}</p>
        \${context ? \`<p class="step-meta">\${escapeHtml(context)}</p>\` : ""}
      </article>
    \`;
  }).join("");

  elements.sessionDetail.className = "session-detail";
  elements.sessionDetail.innerHTML = \`
    <div>
      <p class="panel-label">Session</p>
      <h3>\${escapeHtml(session.primaryApplication)}</h3>
      <p class="muted">\${escapeHtml(formatDateTime(session.startTime))} to \${escapeHtml(formatDateTime(session.endTime))}</p>
      <p class="muted">Boundary: \${escapeHtml(session.sessionBoundaryReason)} | \${escapeHtml(String((session.steps || []).length))} steps</p>
      <div class="step-list">\${steps || '<div class="empty-state">No steps in this session.</div>'}</div>
    </div>
  \`;
}

async function refreshDashboard() {
  setError("");
  elements.refreshButton.disabled = true;

  try {
    syncUrl();
    const response = await fetch(\`/api/viewer/dashboard?\${buildQueryString()}\`);

    if (!response.ok) {
      throw new Error("Failed to load local viewer data.");
    }

    const data = await response.json();
    state.latestDashboard = data;

    if (!state.date) {
      state.date = data.timeWindow.reportDate;
      elements.dateInput.value = state.date;
      syncUrl();
    }

    renderStatus(data.agentHealth, data.generatedAt);
    renderSummaryCards(data);
    renderHighlights(data.report.summary);
    renderSnapshotList(data.latestSnapshots);
    renderComparisonView(data.comparison);
    renderFeedbackWorkflowList(data.reviewableWorkflows);
    renderWorkflowTable(
      elements.workflowList,
      data.report.workflows,
      "No confirmed workflows yet. Keep collecting data or switch to the week window.",
      false,
    );
    renderEmergingWorkflowList(
      elements.emergingWorkflowList,
      data.report.emergingWorkflows,
      "No emerging workflows yet for this window.",
    );
    await refreshAnalysisPanel(data);
    await refreshWorkflowDetail();
    renderSessionList(data.sessionSummaries);
    await refreshSessionDetail();
  } catch (error) {
    setError(error instanceof Error ? error.message : "Unknown viewer error");
  } finally {
    elements.refreshButton.disabled = false;
  }
}

function scheduleRefresh() {
  if (state.refreshTimer) {
    window.clearInterval(state.refreshTimer);
  }

  state.refreshTimer = window.setInterval(() => {
    void refreshDashboard();
  }, 30000);
}

function bindEvents() {
  for (const button of elements.viewButtons) {
    button.addEventListener("click", () => {
      const nextView = button.getAttribute("data-view-target");

      if (nextView !== "overview" && nextView !== "review" && nextView !== "analysis") {
        return;
      }

      state.view = nextView;
      syncView();
      syncUrl();

      if (state.view === "analysis" && state.latestDashboard) {
        void refreshAnalysisPanel();
      }
    });
  }

  elements.windowSelect.addEventListener("change", () => {
    state.window = elements.windowSelect.value;
    void refreshDashboard();
  });

  elements.dateInput.addEventListener("change", () => {
    state.date = elements.dateInput.value;
    void refreshDashboard();
  });

  elements.refreshButton.addEventListener("click", () => {
    void refreshDashboard();
  });
}

initializeStateFromUrl();
syncView();
bindEvents();
scheduleRefresh();
void refreshDashboard();
`;
}
