import type { ActionPackDefinition } from "../types.js";

export const googleMailActionPack: ActionPackDefinition = {
  id: "google-mail",
  version: 1,
  priority: 88,
  rules: [
    {
      id: "open-mailbox",
      layer: "domain_pack",
      domainPackIds: ["google-mail"],
      routeFamilies: ["google-mail.mailbox.list"],
      eventTypes: ["page_navigation", "application_switch"],
      actionName: "open_inbox",
      confidence: 0.93,
    },
    {
      id: "search-mail",
      layer: "domain_pack",
      domainPackIds: ["google-mail"],
      routeFamilies: ["google-mail.search.results"],
      eventTypes: ["page_navigation", "application_switch"],
      actionName: "search_mail",
      confidence: 0.94,
    },
    {
      id: "open-mail-thread",
      layer: "domain_pack",
      domainPackIds: ["google-mail"],
      routeFamilies: ["google-mail.thread.detail"],
      eventTypes: ["page_navigation", "application_switch"],
      actionName: "open_mail_thread",
      confidence: 0.95,
    },
    {
      id: "compose-mail",
      layer: "domain_pack",
      domainPackIds: ["google-mail"],
      routeFamilies: ["google-mail.compose"],
      eventTypes: ["page_navigation", "application_switch"],
      actionName: "compose_mail",
      confidence: 0.93,
    },
    {
      id: "reply-mail-thread",
      layer: "domain_pack",
      domainPackIds: ["google-mail"],
      routeFamilies: ["google-mail.thread.detail"],
      targetIncludes: ["reply", "reply_send", "send_reply"],
      requireExplicitTarget: true,
      actionName: "reply_mail_thread",
      confidence: 0.96,
    },
    {
      id: "archive-mail-thread",
      layer: "domain_pack",
      domainPackIds: ["google-mail"],
      routeFamilies: ["google-mail.thread.detail"],
      targetIncludes: ["archive", "archive_thread"],
      requireExplicitTarget: true,
      actionName: "archive_mail_thread",
      confidence: 0.95,
    },
  ],
};
