import type { ActionPackDefinition } from "../types.js";

export const makestarAdminActionPack: ActionPackDefinition = {
  id: "makestar-admin",
  version: 1,
  priority: 100,
  rules: [
    {
      id: "edit-product",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      routeFamilies: ["makestar-admin.products.edit"],
      eventTypes: ["page_navigation", "button_click", "form_submit"],
      actionName: "edit_product",
      confidence: 0.98,
    },
    {
      id: "open-admin-order",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      routeFamilies: ["makestar-admin.orders.detail", "makestar-admin.orders.list"],
      eventTypes: ["page_navigation", "application_switch"],
      actionName: "open_admin",
      confidence: 0.91,
    },
    {
      id: "open-admin-refund",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      routeFamilies: ["makestar-admin.refunds.review"],
      eventTypes: ["page_navigation", "application_switch"],
      actionName: "open_admin",
      confidence: 0.9,
    },
    {
      id: "search-order",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      targetIncludes: ["search_order", "order_search"],
      actionName: "search_order",
      confidence: 0.98,
    },
    {
      id: "update-status",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      targetIncludes: ["status", "approve_refund", "reschedule_delivery"],
      actionName: "update_status",
      confidence: 0.95,
    },
    {
      id: "notify-customer",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      targetIncludes: ["notify_customer", "send_confirmation", "send_email"],
      actionName: "notify_customer",
      confidence: 0.94,
    },
    {
      id: "export-excel-download",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      eventTypes: ["file_download"],
      actionName: "export_excel",
      confidence: 0.97,
    },
    {
      id: "export-excel-target",
      layer: "domain_pack",
      domainPackIds: ["makestar-admin"],
      targetIncludes: ["export", "download", "orders_csv"],
      actionName: "export_excel",
      confidence: 0.93,
    },
  ],
};
